import Proofs.GraphQL.IncrementalDelivery.WorkQueueImplementation.ChildStreamRelease
import Proofs.GraphQL.IncrementalDelivery.WorkQueueImplementation.StreamSourceOrder

/-! Stored child-stream links identify the generating occurrence in the original work. -/

namespace GraphQL.IncrementalDelivery.ReferenceWorkQueue
open GraphQL.IncrementalDelivery.Execution (StreamItemValue WorkQueueEvent)
open GraphQL.IncrementalDelivery.WorkQueueSemantics

-----------------------------------------------------------------------------------------
-- Immediate stream lowering preserves the structural producer
-----------------------------------------------------------------------------------------

/-- Every immediately lowered stream inherits its subtree's producer and enclosing owners.
Witness: traverse only combine nodes; lowering stops at task and stream boundaries. -/
theorem workFromSpec_streams_nodeAt {root current : Execution.Work}
    {address producer enclosing}
    (located : Located root address current producer enclosing) {stream : Stream}
    (member : stream ∈ (Work.fromExecution current address).streams)
    : NodeAt root stream.node .stream enclosing producer := by
  cases current with
  | empty => simp [Work.fromExecution] at member
  | combine left right =>
      simp only [Work.fromExecution, Work.combine, List.mem_append] at member
      rcases member with left | right
      · exact workFromSpec_streams_nodeAt located.left left
      · exact workFromSpec_streams_nodeAt located.right right
  | executionGroup => simp [Work.fromExecution] at member
  | stream node items =>
      simp only [Work.fromExecution, List.mem_singleton] at member
      subst stream
      exact ⟨address, items, located⟩
termination_by sizeOf current
decreasing_by
  all_goals simp_wf
  all_goals subst current
  all_goals simp [sizeOf, Execution.Work._sizeOf_1]
  all_goals omega

/-- A task-success payload's immediate streams name that task as their structural producer.
Witness: source matching fixes child lowering at the successful task's child address.
-/
theorem GraphEvent.MatchesWork.childStream_producer {work occurrence result}
    (matching : (GraphEvent.taskSuccess occurrence result).MatchesWork work)
    {stream : Stream} (member : stream ∈ result.work.streams)
    : ∃ dependencies, NodeAt work stream.node .stream dependencies (some occurrence) := by
  obtain ⟨owners, producer, known, _, childrenWork⟩ := matching
  cases occurrence with
  | item address index => cases childrenWork
  | executionGroup address =>
      obtain ⟨groups, path, outcome, children, enclosing, located, _, _⟩ := known
      change locateWork work address = some
        ⟨.executionGroup groups path outcome children, producer, enclosing⟩ at located
      have childLowering : result.work = Work.fromExecution children (address ++ [0]) := by
        simpa [taskChildWork?, located] using childrenWork.symm
      rw [childLowering] at member
      exact ⟨_, workFromSpec_streams_nodeAt (Located.executionGroup located) member⟩

/-- Generated stream refs determine the producer as well as the structural address.
Witness: allocation-ref uniqueness identifies the location; deterministic lookup then
identifies the producer, without any assumption about scheduling or publication. -/
theorem ExecutedWork.streamProducer_unique {work : Execution.Work}
    (generated : ExecutedWork work)
    {first second firstOwners secondOwners firstProducer secondProducer}
    (firstAt : NodeAt work first .stream firstOwners firstProducer)
    (secondAt : NodeAt work second .stream secondOwners secondProducer)
    (sameRef : first.ref = second.ref)
    : firstProducer = secondProducer := by
  obtain ⟨left, firstItems, firstLocated⟩ := firstAt
  obtain ⟨right, secondItems, secondLocated⟩ := secondAt
  have sameAddress := generated.streamAddress_unique firstLocated secondLocated sameRef
  subst right
  have same := Option.some.inj (firstLocated.symm.trans secondLocated)
  exact congrArg WorkLocation.producer same

-----------------------------------------------------------------------------------------
-- Each stored child ref refers to a stream generated by its owning task node
-----------------------------------------------------------------------------------------

/-- Child-stream refs on live task nodes retain structural producer evidence in `work`.
The existential node descriptor keeps raw work permissive; generated ref uniqueness
later identifies this producer with any descriptor for the same stream ref. -/
def State.ChildStreamsMatchWork (queue : State) (work : Execution.Work) : Prop :=
  ∀ task ∈ queue.taskNodes,
  ∀ ref ∈ task.childStreams,
    ∃ stream dependencies,
      NodeAt work stream .stream dependencies (some task.task.occurrence)
      ∧ stream.ref = ref

/-- Pointwise preservation lifts through executable left folds.
Witness: induction processes each entry in the implementation's actual order. -/
private theorem fold_preserves {α β : Type} (property : α → Prop) (step : α → β → α)
    (preserved : ∀ state item, property state → property (step state item))
    (items : List β) (state : α) (initial : property state)
    : property (items.foldl step state) := by
  induction items generalizing state with
  | nil => exact initial
  | cons item rest ih => exact ih _ (preserved state item initial)

/-- Group-node replacement leaves child-stream provenance untouched.
Witness: the task-node map is unchanged. -/
theorem State.ChildStreamsMatchWork.putGroupNode {queue : State} {work : Execution.Work}
    (matching : queue.ChildStreamsMatchWork work) (updated : GroupNode)
    : (queue.putGroupNode updated).ChildStreamsMatchWork work :=
  matching

/-- A task-node replacement preserves provenance when its retained links are justified.
Witness: each mapped node is the replacement or an unchanged old node. -/
theorem State.ChildStreamsMatchWork.putTaskNode {queue : State} {work : Execution.Work}
    (matching : queue.ChildStreamsMatchWork work) (updated : TaskNode)
    (known
      : ∀ ref ∈ updated.childStreams,
          ∃ stream dependencies,
            NodeAt work stream .stream dependencies (some updated.task.occurrence)
            ∧ stream.ref = ref)
    : (queue.putTaskNode updated).ChildStreamsMatchWork work := by
  intro task member
  obtain ⟨old, oldMember, same⟩ := List.mem_map.mp member
  split at same
  · subst task
    exact known
  · subst task
    exact matching old oldMember

/-- Group integration changes no stored task links.
Witness: exact task-map preservation during group registration and parent linking. -/
theorem State.ChildStreamsMatchWork.addGroups {queue : State} {work : Execution.Work}
    (matching : queue.ChildStreamsMatchWork work) (groups : List Group)
    : (queue.addGroups groups).1.ChildStreamsMatchWork work := by
  intro task member
  rw [State.addGroups_taskNodes] at member
  exact matching task member

/-- Newly started task nodes have no child links; old nodes retain their provenance.
Witness: the registration handler's old-or-new node characterization. -/
theorem State.ChildStreamsMatchWork.addTask {queue : State} {work : Execution.Work}
    (matching : queue.ChildStreamsMatchWork work) (task : Task)
    : (queue.addTask task).ChildStreamsMatchWork work := by
  intro node member ref linked
  rcases queue.addTask_startedOldOrNew task member with old | new
  · exact matching node old ref linked
  · subst node
    cases linked

/-- Fresh stream selection retains only supplied stream descriptors.
Witness: the deduplication fold either skips a candidate or appends that exact input. -/
theorem freshStreams_subset (queue : State) (streams : List Stream)
    : (streams.foldl
        (fun selected stream =>
          if (queue.stream? stream.node.ref).isSome
              || selected.any (fun known => known.node.ref == stream.node.ref) then
            selected
          else
            selected ++ [stream])
        []).Subset
        streams := by
  let step (selected : List Stream) (stream : Stream) :=
    if (queue.stream? stream.node.ref).isSome
        || selected.any (fun known => known.node.ref == stream.node.ref) then selected
    else selected ++ [stream]
  have loop (remaining selected : List Stream) (old : selected.Subset streams)
      (inputs : remaining.Subset streams) : (remaining.foldl step selected).Subset streams := by
    induction remaining generalizing selected with
    | nil => exact old
    | cons stream rest ih =>
        apply ih
        · dsimp only [step]
          split
          · exact old
          · intro candidate member
            rcases List.mem_append.mp member with earlier | added
            · exact old earlier
            · exact List.mem_singleton.mp added ▸ inputs List.mem_cons_self
        · intro candidate member
          exact inputs (List.mem_cons_of_mem _ member)
  exact loop streams [] (by intro _ impossible; cases impossible) (List.Subset.refl _)

/-- Stream integration attaches only refs whose structural producer is the selected task.
Witness: fresh candidates are supplied inputs; old links and the producer occurrence
are retained by the node update. Parentless integration changes no task links. -/
theorem State.ChildStreamsMatchWork.addStreams {queue : State} {work : Execution.Work}
    (matching : queue.ChildStreamsMatchWork work) (streams : List Stream)
    (parent : Option Occurrence)
    (known
      : ∀ occurrence,
          parent = some occurrence
          → ∀ stream ∈ streams,
              ∃ dependencies,
                NodeAt work stream.node .stream dependencies (some occurrence))
    : (queue.addStreams streams parent).1.ChildStreamsMatchWork work := by
  cases parent with
  | none => exact matching
  | some occurrence =>
      simp only [State.addStreams]
      split
      · exact matching
      · rename_i node found
        have source := State.taskNode?_some (queue := queue) found
        apply matching.putTaskNode
        intro ref member
        rcases List.mem_append.mp member with old | added
        · exact matching node source.1 ref old
        · obtain ⟨stream, fresh, same⟩ := List.mem_map.mp added
          obtain ⟨dependencies, structural⟩ :=
            known occurrence rfl stream (freshStreams_subset queue streams fresh)
          exact ⟨stream.node, dependencies, source.2 ▸ structural, same⟩

/-- Immediate work integration preserves old links and installs justified producer links.
Witness: group and task integration followed by exact stream attachment. -/
theorem State.ChildStreamsMatchWork.maybeIntegrateWork {queue : State}
    {work : Execution.Work} (matching : queue.ChildStreamsMatchWork work) (newWork : Work)
    (parent : Option Occurrence := none)
    (known
      : ∀ occurrence,
          parent = some occurrence
          → ∀ stream ∈ newWork.streams,
              ∃ dependencies,
                NodeAt work stream.node .stream dependencies (some occurrence))
    : (queue.maybeIntegrateWork newWork parent).1.ChildStreamsMatchWork work := by
  have tasks := fold_preserves (fun current => current.ChildStreamsMatchWork work) State.addTask
    (fun _ task prior => prior.addTask task) newWork.tasks _ (matching.addGroups newWork.groups)
  exact tasks.addStreams newWork.streams parent known

-----------------------------------------------------------------------------------------
-- Cleanup, starts, and graph-event handlers preserve structural stream links
-----------------------------------------------------------------------------------------

/-- Parentless integration attaches no new streams to task nodes.
Witness: the producer-side condition of integration is vacuous. -/
theorem State.ChildStreamsMatchWork.integrateRoots {queue : State} {work : Execution.Work}
    (matching : queue.ChildStreamsMatchWork work) (newWork : Work)
    : (queue.maybeIntegrateWork newWork).1.ChildStreamsMatchWork work :=
  matching.maybeIntegrateWork newWork none (by intro _ impossible; cases impossible)

/-- Pruning leaves the complete task-node map unchanged.
Witness: the existing exact equation for the bounded pruning loop. -/
theorem State.ChildStreamsMatchWork.pruneEmptyGroups {queue : State}
    {work : Execution.Work} (matching : queue.ChildStreamsMatchWork work)
    (groups : List Execution.DeliveryNode)
    : (queue.pruneEmptyGroups groups).1.ChildStreamsMatchWork work := by
  intro task member
  rw [State.pruneEmptyGroups_taskNodes] at member
  exact matching task member

/-- Starting a task can only add a node without child streams.
Witness: old nodes are unchanged, and the appended default node has an empty link list.
-/
theorem State.ChildStreamsMatchWork.startTask {queue : State} {work : Execution.Work}
    (matching : queue.ChildStreamsMatchWork work) (occurrence : Occurrence)
    : (queue.startTask occurrence).ChildStreamsMatchWork work := by
  unfold State.startTask
  split
  · exact matching
  · split
    · exact matching
    · intro task member ref linked
      rcases List.mem_append.mp member with old | new
      · exact matching task old ref linked
      · have same := List.mem_singleton.mp new
        subst task
        cases linked

/-- Starting a group's tasks preserves provenance throughout the membership fold.
Witness: each task start introduces no new child links. -/
theorem State.ChildStreamsMatchWork.startGroup {queue : State} {work : Execution.Work}
    (matching : queue.ChildStreamsMatchWork work) (ref : NodeRef)
    : (queue.startGroup ref).ChildStreamsMatchWork work := by
  unfold State.startGroup
  split
  · exact matching
  · split
    · exact matching
    · exact fold_preserves (fun queue => queue.ChildStreamsMatchWork work) State.startTask
        (fun _ occurrence prior => prior.startTask occurrence) _ _ matching

/-- Starting a stream changes only the active stream-ref list.
Witness: neither branch rewrites task nodes. -/
theorem State.ChildStreamsMatchWork.startStream {queue : State} {work : Execution.Work}
    (matching : queue.ChildStreamsMatchWork work) (ref : NodeRef)
    : (queue.startStream ref).ChildStreamsMatchWork work := by
  unfold State.startStream
  split <;> exact matching

/-- Activating released work retains structural evidence for all task stream links.
Witness: compose the actual group-start and stream-start folds. -/
theorem State.ChildStreamsMatchWork.startNewWork {queue : State} {work : Execution.Work}
    (matching : queue.ChildStreamsMatchWork work) (newWork : NewWork)
    : (queue.startNewWork newWork).ChildStreamsMatchWork work := by
  let current :=
    { queue with
      rootGroups := queue.rootGroups ++ newWork.newGroups.map Execution.DeliveryNode.ref }
  have groups := fold_preserves (fun queue => queue.ChildStreamsMatchWork work) State.startGroup
    (fun _ ref prior => prior.startGroup ref)
    (newWork.newGroups.map Execution.DeliveryNode.ref) current matching
  exact fold_preserves (fun queue => queue.ChildStreamsMatchWork work) State.startStream
    (fun _ ref prior => prior.startStream ref) _ _ groups

/-- Failed-group cleanup keeps only existing task nodes and their original links.
Witness: membership in the retained task-node filter. -/
theorem State.ChildStreamsMatchWork.removeGroup {queue : State} {work : Execution.Work}
    (matching : queue.ChildStreamsMatchWork work) (ref : NodeRef)
    : (queue.removeGroup ref).ChildStreamsMatchWork work :=
  fun node member => matching node (List.mem_filter.mp member).1

/-- Successful group flushing cannot change a surviving task's child-stream producer.
Witness: the selected-node flush witness gives residual task-map inclusion. -/
theorem State.ChildStreamsMatchWork.finishGroupSuccess {queue : State}
    {work : Execution.Work} (matching : queue.ChildStreamsMatchWork work)
    (group : GroupNode)
    : (queue.finishGroupSuccess group).1.ChildStreamsMatchWork work := by
  obtain ⟨_, _, _, _, retained, _⟩ := queue.finishGroupSuccess_publications group
  exact fun node member => matching node (retained member)

/-- Recursive draining preserves every surviving child stream's structural producer.
Witness: successful and failed cleanup retain old task nodes; starts create no child links.
-/
theorem State.ChildStreamsMatchWork.drainReadyGroups {queue : State}
    {work : Execution.Work} (matching : queue.ChildStreamsMatchWork work)
    : queue.drainReadyGroups.1.ChildStreamsMatchWork work := by
  apply State.drainReadyGroups_preserves
    (fun current => current.ChildStreamsMatchWork work) (valid := matching)
  · intro current node prior _ _ _ _
    exact (prior.finishGroupSuccess node).startNewWork _
  · intro current node errors prior _ _ _
    exact prior.removeGroup _

/-- Matched task success attaches streams to their exact structural producer.
Witness: value replacement preserves old links; matched child lowering justifies new
links before the contributor fold and final drain release work. -/
theorem State.ChildStreamsMatchWork.taskSuccess {queue : State} {work : Execution.Work}
    (matching : queue.ChildStreamsMatchWork work) {occurrence result}
    (source : (GraphEvent.taskSuccess occurrence result).MatchesWork work)
    : (queue.taskSuccess occurrence result).1.ChildStreamsMatchWork work := by
  cases found : queue.taskNode? occurrence with
  | none => simpa only [State.taskSuccess, found] using matching
  | some node =>
      have member := (State.taskNode?_some found).1
      have installed := matching.putTaskNode { node with value := some result.value }
        (matching node member)
      have integrated := installed.maybeIntegrateWork result.work (some occurrence) (by
        intro other same stream supplied
        cases same
        exact source.childStream_producer supplied)
      have step (acc : State × List WorkQueueEvent × NewWork) (group : Execution.DeliveryNode)
          (prior : acc.1.ChildStreamsMatchWork work)
          : (successGroupStep acc group).1.ChildStreamsMatchWork work := by
        obtain ⟨current, events, released⟩ := acc
        dsimp only [successGroupStep]
        split
        · exact prior
        · split
          · exact (prior.putGroupNode _).finishGroupSuccess _
          · exact prior
      have processed := fold_preserves (fun acc => acc.1.ChildStreamsMatchWork work)
        successGroupStep step node.task.groups (_, [], {}) integrated
      rw [queue.taskSuccess_eq occurrence result node found]
      split
      · exact fun node member => matching node (List.mem_filter.mp member).1
      exact (processed.startNewWork _).drainReadyGroups

/-- Task failure cannot reassign a stream producer.
Witness: initial task deletion followed by cleanup or task-map-preserving cache updates.
-/
theorem State.ChildStreamsMatchWork.taskFailure {queue : State} {work : Execution.Work}
    (matching : queue.ChildStreamsMatchWork work) (occurrence : Occurrence) (errors : Nat)
    : (queue.taskFailure occurrence errors).1.ChildStreamsMatchWork work := by
  unfold State.taskFailure
  split
  · exact matching
  · split
    · exact fun node member => matching node (List.mem_filter.mp member).1
    apply fold_preserves
      (fun acc : State × List WorkQueueEvent => acc.1.ChildStreamsMatchWork work)
    · intro acc group prior
      obtain ⟨current, events⟩ := acc
      dsimp only
      split
      · exact prior
      · split
        · exact prior.removeGroup _
        · exact prior
    · exact fun node member => matching node (List.mem_filter.mp member).1

/-- Stream-item child integration does not attach streams to task nodes.
Witness: each item uses parentless integration; pruning, activation, and draining retain links.
-/
theorem State.ChildStreamsMatchWork.streamItems {queue : State} {work : Execution.Work}
    (matching : queue.ChildStreamsMatchWork work) (stream : Execution.DeliveryNode)
    (items : List StreamItem)
    : (queue.streamItems stream items).1.ChildStreamsMatchWork work := by
  let step (acc : State × List Execution.DeliveryNode
      × List Execution.DeliveryNode × List StreamItemValue) (item : StreamItem) :=
    let (current, groups, streams, values) := acc
    let (integrated, newWork) := current.maybeIntegrateWork item.work
    let (pruned, nonempty) := integrated.pruneEmptyGroups newWork.newGroups
    (pruned.startNewWork { newWork with newGroups := nonempty },
      groups ++ nonempty, streams ++ newWork.newStreams, values ++ [item.value])
  have folded := fold_preserves (fun acc => acc.1.ChildStreamsMatchWork work) step
    (fun acc item prior => ((prior.integrateRoots item.work).pruneEmptyGroups _).startNewWork _)
    items (queue, [], [], []) matching
  unfold State.streamItems
  split
  · exact matching
  · exact folded.drainReadyGroups

/-- Every matching graph event preserves the structural meaning of stored child refs.
Witness: task success is the sole attachment path; other handlers retain or remove links.
-/
theorem State.ChildStreamsMatchWork.handleGraphEvent {queue : State}
    {work : Execution.Work} (matching : queue.ChildStreamsMatchWork work)
    {event : GraphEvent} (source : event.MatchesWork work)
    : (queue.handleGraphEvent event).1.ChildStreamsMatchWork work := by
  cases event with
  | taskSuccess => exact matching.taskSuccess source
  | taskFailure occurrence errors => exact matching.taskFailure occurrence errors
  | streamItems stream items => exact matching.streamItems stream items
  | streamSuccess stream =>
      simp only [State.handleGraphEvent, State.streamSuccess]
      split <;> exact matching
  | streamFailure stream errors =>
      simp only [State.handleGraphEvent, State.streamFailure]
      split <;> exact matching

-----------------------------------------------------------------------------------------
-- Actual normalized replay supplies provenance without extra state premises
-----------------------------------------------------------------------------------------

/-- Initialization has no task-produced stream links, regardless of immediate work shape.
Witness: start from an empty task map and integrate only root streams. -/
theorem createWorkQueue_childStreamsMatchWork (initial : Work) (work : Execution.Work)
    : (State.initialize initial).ChildStreamsMatchWork work := by
  have empty : ({} : State).ChildStreamsMatchWork work := by
    simp [State.ChildStreamsMatchWork]
  exact ((empty.integrateRoots initial).pruneEmptyGroups _).startNewWork _

/-- Every matching input batch preserves stored stream provenance through termination.
Witness: the actual event fold followed by the wrapper's terminal-flag update. -/
theorem State.ChildStreamsMatchWork.handleGraphEvents {queue : State}
    {work : Execution.Work} (matching : queue.ChildStreamsMatchWork work)
    (events : List GraphEvent) (sources : ∀ event ∈ events, event.MatchesWork work)
    : (queue.handleGraphEvents events).1.ChildStreamsMatchWork work := by
  have loop (remaining : List GraphEvent) (acc : State × List WorkQueueEvent)
      (prior : acc.1.ChildStreamsMatchWork work)
      (known : ∀ event ∈ remaining, event.MatchesWork work)
      : (remaining.foldl rawEventStep acc).1.ChildStreamsMatchWork work := by
    induction remaining generalizing acc with
    | nil => exact prior
    | cons event rest ih =>
        exact ih _ (prior.handleGraphEvent (known event List.mem_cons_self))
          (fun next member => known next (List.mem_cons_of_mem _ member))
  have folded := loop events (queue, []) matching sources
  rw [State.handleGraphEvents_eq_rawEventReplay]
  split
  · exact matching
  · dsimp only
    split <;> exact folded

/-- Valid host input suffices for stream-link provenance throughout actual normalized replay.
Witness: source matching justifies each attachment and the publisher leaves queue state
unchanged. No generated-work, initialization, freshness-derived, or start premise is added.
-/
theorem createWorkQueue_runNormalized_childStreamsMatchWork {work : Execution.Work}
    {batches : List (List GraphEvent)} (valid : ValidGraphEvents work batches.flatten)
    : ((State.initialize (Work.fromExecution work)).runNormalized
        batches).1.ChildStreamsMatchWork
        work := by
  have loop (remaining : List (List GraphEvent)) (acc : NormalizedAcc)
      (prior : acc.1.ChildStreamsMatchWork work)
      (sources : ∀ event ∈ remaining.flatten, event.MatchesWork work)
      : (remaining.foldl normalizedStep acc).1.ChildStreamsMatchWork work := by
    induction remaining generalizing acc with
    | nil => exact prior
    | cons batch rest ih =>
        have current : (normalizedStep acc batch).1.ChildStreamsMatchWork work := by
          rw [normalizedStep_queue]
          exact prior.handleGraphEvents batch (fun event member =>
            sources event (List.mem_append_left _ member))
        exact ih _ current
          (fun event member => sources event (List.mem_append_right _ member))
  exact loop batches
    (
      State.initialize (Work.fromExecution work),
      {
        active :=
          (State.initialize (Work.fromExecution work)).initialGroups
          ++ (State.initialize (Work.fromExecution work)).initialStreams
      },
      []
    )
    (createWorkQueue_childStreamsMatchWork _ _)
    (fun _ member => valid.event_matches member)

-----------------------------------------------------------------------------------------
-- Stored links and release witnesses identify the structural producer
-----------------------------------------------------------------------------------------

/-- A stored link identifies the unique producer of any generated stream with that ref.
Witness: link provenance supplies one stream descriptor, and allocation uniqueness
equates its producer with the independently supplied structural descriptor. -/
theorem State.ChildStreamsMatchWork.producer {queue : State} {work : Execution.Work}
    (matching : queue.ChildStreamsMatchWork work) (generated : ExecutedWork work)
    {node : TaskNode} (member : node ∈ queue.taskNodes)
    {stream dependencies producer}
    (known : NodeAt work stream .stream dependencies producer)
    (linked : stream.ref ∈ node.childStreams)
    : producer = some node.task.occurrence := by
  obtain ⟨descriptor, owners, structural, sameRef⟩ := matching node member stream.ref linked
  exact generated.streamProducer_unique known structural sameRef.symm

/-- A released generated stream's producer is the task whose value precedes its notice.
Witness: the exact normalized flush witness, stored-link provenance, and generated
stream-ref uniqueness. The supplied stream descriptor may come from a later source event.
-/
theorem State.ChildStreamsMatchWork.finishGroupSuccess_producer_release
    {queue : State} {work : Execution.Work} (matching : queue.ChildStreamsMatchWork work)
    (settled : queue.ChildStreamsSettled) (generated : ExecutedWork work)
    (publisher : IncrementalPublisher) (group : GroupNode) {stream dependencies producer}
    (known : NodeAt work stream .stream dependencies producer)
    (released : stream ∈ (queue.finishGroupSuccess group).2.2.newStreams)
    : ∃ node ∈ queue.taskNodes,
        ∃ value,
          producer = some node.task.occurrence
          ∧ node.value = some value
          ∧ [
              Execution.WorkQueueEvent.groupValues
                (publisher.getBestIdAndSubPath group.group.node value) [value],
              .groupSuccess group.group.node
                (queue.finishGroupSuccess group).2.2.newGroups
                (queue.finishGroupSuccess group).2.2.newStreams
            ].Sublist
              (publisher.normalizeBatch (queue.finishGroupSuccess group).2.1).2 := by
  obtain ⟨node, member, value, _, linked, stored, ordered⟩ :=
    settled.finishGroupSuccess_normalized_release publisher group released
  exact ⟨node, member, value, matching.producer generated member known linked, stored, ordered⟩

/-- After valid replay, local stream release publishes an exact value of its structural
producer before the notice. Witness: replay establishes both link invariants and stored
input provenance; matched task outcomes justify the producer's value annotation.
This local ordering has not yet been transported to the full output-history matching.
-/
theorem createWorkQueue_runNormalized_streamProducerRelease {work : Execution.Work}
    {batches : List (List GraphEvent)} (generated : ExecutedWork work)
    (valid : ValidGraphEvents work batches.flatten) (publisher : IncrementalPublisher)
    (group : GroupNode) {stream dependencies producer}
    (known : NodeAt work stream .stream dependencies producer)
    (released
      : stream
        ∈ (((State.initialize (Work.fromExecution work)).runNormalized
              batches).1.finishGroupSuccess
            group).2.2.newStreams)
    : let queue := ((State.initialize (Work.fromExecution work)).runNormalized batches).1
      ∃ occurrence value,
        producer = some occurrence
        ∧ ObjectValueFrom batches.flatten occurrence value
        ∧ PublicationAt work occurrence
            (.groupValues (publisher.getBestIdAndSubPath group.group.node value) [value])
        ∧ [
            Execution.WorkQueueEvent.groupValues
              (publisher.getBestIdAndSubPath group.group.node value) [value],
            .groupSuccess group.group.node
              (queue.finishGroupSuccess group).2.2.newGroups
              (queue.finishGroupSuccess group).2.2.newStreams
          ].Sublist
            (publisher.normalizeBatch (queue.finishGroupSuccess group).2.1).2 := by
  have links := createWorkQueue_runNormalized_childStreamsMatchWork valid
  have settled := createWorkQueue_runNormalized_childStreamsSettled (Work.fromExecution work) batches
  obtain ⟨node, member, value, producer, stored, ordered⟩ :=
    links.finishGroupSuccess_producer_release settled generated publisher group known released
  obtain ⟨_, _, inventory⟩ := createWorkQueue_runNormalized_publications valid
  obtain ⟨source, supplied, exactValue⟩ := (inventory.stored node member value stored).1
  obtain ⟨owners, birth, taskAt, _, _⟩ := valid.event_matches supplied
  refine ⟨
    node.task.occurrence,
    value,
    producer,
    ⟨source, supplied, exactValue⟩,
    ?_,
    ordered
  ⟩
  exact ⟨owners, birth, by simpa only [exactValue] using taskAt⟩

end GraphQL.IncrementalDelivery.ReferenceWorkQueue
