import Proofs.GraphQL.IncrementalDelivery.WorkQueueImplementation.ObjectPublicationAcceptance
import Proofs.GraphQL.IncrementalDelivery.WorkQueueImplementation.ProducedStreamReleaseCoverage
import Proofs.GraphQL.IncrementalDelivery.WorkQueueImplementation.TerminalObjectProducedGroups

/-! Every canonical object publication releases every stream generated by that object. -/

namespace GraphQL.IncrementalDelivery.ReferenceWorkQueue.ConformancePlan
open GraphQL.IncrementalDelivery.WorkQueueSemantics

-----------------------------------------------------------------------------------------
-- Raw successful carrier health applies to the exact canonical occurrence
-----------------------------------------------------------------------------------------

/-- Every stream generated by a canonical object atom occurs in actual raw notices.
Witness: register the same matched task at its raw release handler, recover its successful
source input, and use healthy retirement to force complete stream release. The publisher's
reported owner may differ from the raw carrier; the proof retains both without conflation.
-/
theorem Witness.groupPublication_childStream_rawNotice
    {work inputs w index owner payload stream dependencies}
    (generated : ExecutedWork work) (valid : ValidGraphEvents work inputs.flatten)
    (started : inputsStarted work inputs = true)
    (history : w.events = (initialQueue work).nonterminalAtoms inputs)
    (ledger : BufferedClosureLedger work inputs w)
    (selected : w.events[index]? = some (.groupValues owner payload))
    (child : NodeAt work stream .stream dependencies (some (w.matching index)))
    : stream.ref
      ∈ ((initialQueue work).rawEventReplay inputs.flatten).2.flatMap
          rawStreamNoticeRefs := by
  obtain ⟨origin⟩ := Witness.groupPublication_origin started history selected
  obtain ⟨boundary⟩ := origin.handlerBoundary
  obtain ⟨task, registered, identity⟩ := Witness.groupPublication_registered_at_handler
    started history ledger selected origin boundary
  have accepted : (initialQueue work).batchesStarted inputs = true := by
    rwa [← inputsStarted_eq_batchesStarted]
  have received := (initialQueue work).batchesStarted_acceptsBatch inputs accepted
  have prior : (boundary.before ++ [boundary.event]).IsPrefix inputs.flatten :=
    ⟨boundary.after, by simp [boundary.sourceEq, List.append_assoc]⟩
  have priorAccepted : (initialQueue work).acceptsBatch
      (boundary.before ++ [boundary.event]) = true := by
    apply State.acceptsBatch_prefix (after := boundary.after)
    simpa only [boundary.sourceEq, List.append_assoc, List.singleton_append] using received
  obtain ⟨groups, streams, carrier⟩ :=
    (((initialQueue work).replayGraphEvents boundary.before).handleGraphEvent_publicationPairs
      boundary.event).next boundary.atHandler
  obtain ⟨producer, known⟩ := Witness.groupPublication_taskAt started history ledger selected origin
  have contributes := createWorkQueue_rawEventReplay_publicationContributors valid
    origin.group origin.values origin.members.1 origin.value origin.members.2
  have accounting := (createWorkQueue_pendingAccounting work).replayGraphEvents (before := [])
    generated (boundary.before ++ [boundary.event]) (valid.prefix prior) priorAccepted
  obtain ⟨_, actualPayload, actualProducer, _, actualKnown⟩ :=
    (accounting.matching task registered).1
  have ownersEq := (TaskAt.unique (identity ▸ actualKnown) known).1
  obtain ⟨result, supplied⟩ := generated.successfulCarrier_registeredContributor_succeeded
    (valid.prefix prior) priorAccepted (List.mem_of_getElem? carrier) registered
    (ownersEq.symm ▸ contributes)
  rw [identity] at supplied
  obtain ⟨before, after, split⟩ := List.mem_iff_append.mp supplied
  obtain ⟨_, _, retired, healthy, uncancelled⟩ :=
    generated.replayGraphEvents_successfulCarrier_retiredHealthy (valid.prefix prior)
      (State.acceptsBatch_prefix priorAccepted) (List.mem_of_getElem? carrier)
  have noticed := generated.success_retired_childStream_notice (valid.prefix prior) priorAccepted
    known contributes healthy retired uncancelled split child
  have sourceEq : inputs.flatten = (boundary.before ++ [boundary.event]) ++ boundary.after := by
    simp only [boundary.sourceEq, List.append_assoc, List.singleton_append]
  rw [sourceEq, State.rawEventReplay_append]
  simp only [List.flatMap_append]
  exact List.mem_append_left _ noticed

-----------------------------------------------------------------------------------------
-- Public-history publication implies complete child notice coverage
-----------------------------------------------------------------------------------------

/-- Every structural stream generated by a published object is announced on the same witness.
Witness: provenance selects the producer's object atom; complete raw release survives
normalization unchanged. No child notice or release-order premise is supplied.
-/
theorem objectProducedStream_noticed {work inputs w address stream dependencies}
    (generated : ExecutedWork work) (valid : ValidGraphEvents work inputs.flatten)
    (started : inputsStarted work inputs = true)
    (history : w.events = (initialQueue work).nonterminalAtoms inputs)
    (admitted : PublicationAdmission work w)
    (ledger : BufferedClosureLedger work inputs w)
    (known : NodeAt work stream .stream dependencies (some (.executionGroup address)))
    (published : Published w.matching w.events (.executionGroup address))
    : stream.ref ∈ w.events.flatMap streamNoticeRefs := by
  rw [Witness.streamNotices_eq_raw valid started history]
  obtain ⟨index, event, selected, value, same⟩ := published
  have exactValue := same ▸ admitted.publicationAt selected value
  cases event <;> try cases value
  case groupValues owner payload =>
    exact Witness.groupPublication_childStream_rawNotice generated valid started history
      ledger selected (same.symm ▸ known)
  case streamValues node values groups streams =>
    cases values with
    | nil => cases exactValue
    | cons head tail =>
        cases tail with
        | cons next rest => cases exactValue
        | nil =>
            obtain ⟨owners, producer, impossible⟩ := exactValue
            obtain ⟨_, _, _, _, _, _, _, _, payload⟩ := impossible

/-- A stream generated by a published object completes at concrete termination.
Witness: complete object-child notice coverage followed by the existing terminal stream
tracking theorem on the unchanged canonical history and publication matching.
-/
theorem terminal_objectProducedStream_completed
    {work inputs w address stream dependencies} (generated : ExecutedWork work)
    (valid : ValidGraphEvents work inputs.flatten)
    (started : inputsStarted work inputs = true)
    (history : w.events = (initialQueue work).nonterminalAtoms inputs)
    (admitted : PublicationAdmission work w)
    (ledger : BufferedClosureLedger work inputs w)
    (ended : ((initialQueue work).runNormalized inputs).1.terminated = true)
    (known : NodeAt work stream .stream dependencies (some (.executionGroup address)))
    (published : Published w.matching w.events (.executionGroup address))
    : stream.ref ∈ completedRefs w.events :=
  streamNoticeRefs_terminalCompleted valid started history ended
    (List.mem_append_right _
      (objectProducedStream_noticed generated valid started history admitted ledger known
        published))

end GraphQL.IncrementalDelivery.ReferenceWorkQueue.ConformancePlan
