import Proofs.GraphQL.IncrementalDelivery.WorkQueueImplementation.DeferFailureSafety
import Proofs.GraphQL.IncrementalDelivery.WorkQueueSemantics.GroupAccounting

/-! Buffered object producers preserve owner support even in mixed defer/stream work. -/

namespace GraphQL.IncrementalDelivery.ReferenceWorkQueue
open GraphQL.IncrementalDelivery.WorkQueueSemantics
open Semantics.Ancestry Semantics.GeneralScheduling

-----------------------------------------------------------------------------------------
-- Defer continuity is local to an object edge, not a global stream-free restriction
-----------------------------------------------------------------------------------------

/-- A subtree with an object producer retains that producer's defer-owner support.
Witness: invert the last producer edge, then descend through combines. An item edge
cannot be the stated object producer, so unrelated streams need not be excluded.
-/
theorem ExecutedWork.objectProducer_context
    {work address current enclosing source} (generated : ExecutedWork work)
    (located : Located work address current (some (.executionGroup source)) enclosing)
    : ∃ parents bound owners ancestor payload,
        Semantics.MixedKeys.WorkAt parents 0 bound work
        ∧ TaskAt work (.executionGroup source) owners ancestor payload
        ∧ DeferUnder parents owners current := by
  obtain ⟨parents, bound, coherent, continuous, ordered⟩ := generated.producerMetadata
  have context {address current producer enclosing}
      (navigation : StructuralEquivalence.Located work address current producer enclosing)
      (same : producer = some (.executionGroup source))
      : ∃ owners ancestor payload,
          TaskAt work (.executionGroup source) owners ancestor payload
          ∧ DeferUnder parents owners current := by
    induction navigation with
    | root => cases same
    | left _ ih =>
        obtain ⟨owners, ancestor, payload, task, under⟩ := ih same
        exact ⟨owners, ancestor, payload, task, under.1⟩
    | right _ ih =>
        obtain ⟨owners, ancestor, payload, task, under⟩ := ih same
        exact ⟨owners, ancestor, payload, task, under.2⟩
    | executionGroup prior =>
        cases same
        have properties := Correctness.dependencyProperties_located continuous ordered
          prior.toCurrent
        simp only [DeferContinuous] at properties
        exact ⟨_, _, _, .executionGroup prior.toCurrent, properties.1.1⟩
    | item => cases same
  obtain ⟨owners, ancestor, payload, task, under⟩ :=
    context (StructuralEquivalence.located_of_current located) rfl
  exact ⟨parents, bound, owners, ancestor, payload, coherent, task, under⟩

/-- A group generated by an object task reuses or descends from one producer owner.
Witness: local defer continuity plus generated canonical ancestry. Stream items may
occur elsewhere in the work tree, including above this object producer.
-/
theorem ExecutedWork.group_objectProducer_support
    {work node dependencies source} (generated : ExecutedWork work)
    (known : NodeAt work node .group dependencies (some (.executionGroup source)))
    : ∃ owners ancestor payload key,
        TaskAt work (.executionGroup source) owners ancestor payload
        ∧ key ∈ owners
        ∧ (key = node.key ∨ key ∈ dependencies) := by
  obtain ⟨address, groups, path, result, children, enclosing, fragment,
    located, member, sameNode, sameDependencies⟩ := known
  obtain ⟨parents, bound, owners, ancestor, payload, coherent, task, under⟩ :=
    generated.objectProducer_context located
  obtain ⟨key, owner, support⟩ := under.1 fragment member
  refine ⟨owners, ancestor, payload, key, task, owner, ?_⟩
  rcases support with same | dependency
  · exact .inl (same.trans (congrArg Execution.DeliveryNode.key sameNode).symm)
  · have localWork := coherent_located coherent located
    rw [Semantics.MixedKeys.WorkAt] at localWork
    rw [sameDependencies, (localWork.2.1 fragment member).2.2]
    exact .inr dependency

/-- Failure of all object-producer owners fails each object child's contributing owner.
Witness: its supporting producer owner is reused or is an explicit defer dependency.
The producer's value may remain buffered; no publication-readiness premise is used.
-/
theorem ExecutedWork.objectProducer_failure
    {work matching events failures address owners source payload key
      parentOwners ancestor result}
    (generated : ExecutedWork work)
    (known
      : TaskAt work (.executionGroup address) owners
          (some (.executionGroup source)) payload)
    (owner : key ∈ owners)
    (parent : TaskAt work (.executionGroup source) parentOwners ancestor result)
    (failed
      : ∀ parentKey ∈ parentOwners, NodeFailed work matching events failures parentKey)
    : NodeFailed work matching events failures key := by
  obtain ⟨node, dependencies, descriptor, same⟩ := TaskAt.executionGroup_owner known owner
  obtain ⟨supportOwners, birth, value, parentKey, task, contributes, support⟩ :=
    generated.group_objectProducer_support descriptor
  have failure := failed parentKey ((task.unique parent).1 ▸ contributes)
  rcases support with reused | dependency
  · exact (reused.trans same) ▸ failure
  · exact same ▸ NodeFailed.groupDependency descriptor dependency failure

-----------------------------------------------------------------------------------------
-- Only successful item boundaries remain in the mixed producer-cancellation argument
-----------------------------------------------------------------------------------------

/-- Object cancellation fails each owner once earlier successful source items are safe.
Witness: dependency-rank induction propagates cancellation through buffered object
producers; an item producer stops at the explicit item-safety certificate. Source
readiness supplies earlier successes and fixed outcomes rule out failed producers.
This is a proof reduction, not a new host law or a claim of mixed item safety.
-/
theorem ExecutedWork.object_cancelled_owner_failed_of_itemSafety
    {work received matching events failures address owners producer payload key}
    (generated : ExecutedWork work) (valid : ValidGraphEvents work received)
    (failedPayloads
      : ∀ cut occurrence,
          (cut, occurrence) ∈ failures
          → ∃ owners producer payload,
              TaskAt work occurrence owners producer payload
              ∧ payload.failure.isSome = true)
    (itemsSafe
      : ∀ source index,
          Occurrence.item source index ∈ received.flatMap GraphEvent.successes
          → ¬TaskCancelled work matching events failures (.item source index))
    (known : TaskAt work (.executionGroup address) owners producer payload)
    (owner : key ∈ owners)
    (ready
      : ∀ source, producer = some source → source ∈ received.flatMap GraphEvent.successes)
    (cancelled : TaskCancelled work matching events failures (.executionGroup address))
    : NodeFailed work matching events failures key := by
  induction rank : (Occurrence.executionGroup address).dependencyRank
    using Nat.strongRecOn generalizing address owners producer payload key with
  | ind rank ih =>
      obtain ⟨cut, cutMember, reached, cause⟩ := cancelled
      cases cause with
      | owners projected _ _ failed =>
          obtain ⟨birth, result, task⟩ := projected
          exact ⟨cut, cutMember, reached, failed key ((known.unique task).1 ▸ owner)⟩
      | producerFailed projected _ recorded =>
          obtain ⟨otherOwners, result, task⟩ := projected
          have same := (known.unique task).2.1
          have succeeded := valid.successes_succeed (ready _ same)
          exact False.elim (taskSucceeds_not_failedBefore succeeded failedPayloads recorded)
      | @producerCancelled _ parent projected _ cancellation =>
          obtain ⟨otherOwners, result, task⟩ := projected
          have same := (known.unique task).2.1
          have succeeded := ready parent same
          have cancelledParent : TaskCancelled work matching events failures parent :=
            ⟨cut, cutMember, reached, cancellation⟩
          cases parent with
          | item source index =>
              exact False.elim (itemsSafe source index succeeded cancelledParent)
          | executionGroup source =>
              subst producer
              obtain ⟨lower, parentOwners, ancestor, value, parent⟩ := task.producer_dependency
              apply generated.objectProducer_failure known owner parent
              intro parentKey contributes
              apply ih _ (by omega) parent contributes _ cancelledParent rfl
              intro source parentEq
              subst ancestor
              exact valid.groupSettlement_producerBefore parent
                (GraphEvent.successes_mem_settled succeeded)

end GraphQL.IncrementalDelivery.ReferenceWorkQueue
