import Proofs.GraphQL.IncrementalDelivery.WorkQueueImplementation.StreamLoweringCoverage

/-! Buffered successful tasks retain all structural child-stream links. -/

namespace GraphQL.IncrementalDelivery.ReferenceWorkQueue
open GraphQL.IncrementalDelivery.WorkQueueSemantics

-----------------------------------------------------------------------------------------
-- A completeness invariant with one explicitly temporary preparation exception
-----------------------------------------------------------------------------------------

/-- Every value-bearing task retains every stream generated by its occurrence in `work`.
`omitted` exempts only the producer between value installation and child attachment;
ordinary handler boundaries use `none`. This is derived bookkeeping, not a source law.
-/
def State.StoredStreamsComplete (queue : State) (work : Execution.Work)
    (omitted : Option Occurrence := none)
    : Prop :=
  ∀ node ∈ queue.taskNodes,
    node.value.isSome = true
    → omitted ≠ some node.task.occurrence
    → ∀ stream dependencies,
        NodeAt work stream .stream dependencies (some node.task.occurrence)
        → stream.key ∈ node.childStreams

/-- Full coverage also covers all tasks except a chosen temporary producer.
Witness: discard the exception guard and use the complete boundary invariant.
-/
theorem State.StoredStreamsComplete.except {queue : State} {work}
    (complete : queue.StoredStreamsComplete work) (occurrence : Occurrence)
    : queue.StoredStreamsComplete work (some occurrence) :=
  fun node member stored _ => complete node member stored (by simp)

/-- Group replacement and task removal preserve existing stream coverage.
Witness: replacement leaves task nodes unchanged; removal only filters them.
-/
theorem State.StoredStreamsComplete.putGroupNode {queue : State} {work omitted}
    (complete : queue.StoredStreamsComplete work omitted) (updated : GroupNode)
    : (queue.putGroupNode updated).StoredStreamsComplete work omitted :=
  complete

/-- Removing a task retains the original links of every remaining buffered value.
Witness: membership inversion through the executable task-node filter.
-/
theorem State.StoredStreamsComplete.removeTask {queue : State} {work omitted}
    (complete : queue.StoredStreamsComplete work omitted) (occurrence : Occurrence)
    : (queue.removeTask occurrence).StoredStreamsComplete work omitted :=
  fun node member => complete node (List.mem_filter.mp member).1

/-- A replacement preserves coverage if its new value-bearing node has the required links.
Witness: every resulting entry is the replacement or an unchanged old node.
-/
theorem State.StoredStreamsComplete.putTaskNode {queue : State} {work omitted}
    (complete : queue.StoredStreamsComplete work omitted) (updated : TaskNode)
    (allowed
      : updated.value.isSome = true
        → omitted ≠ some updated.task.occurrence
        → ∀ stream dependencies,
            NodeAt work stream .stream dependencies (some updated.task.occurrence)
            → stream.key ∈ updated.childStreams)
    : (queue.putTaskNode updated).StoredStreamsComplete work omitted := by
  intro node member
  obtain ⟨old, included, same⟩ := List.mem_map.mp member
  split at same
  · subst node; exact allowed
  · subst node; exact complete old included

/-- Registering group records leaves the entire task-node map unchanged.
Witness: the exact group-registration projection equation.
-/
theorem State.StoredStreamsComplete.addGroups {queue : State} {work omitted}
    (complete : queue.StoredStreamsComplete work omitted) (groups : List Group)
    : (queue.addGroups groups).1.StoredStreamsComplete work omitted := by
  intro node member
  rw [State.addGroups_taskNodes] at member
  exact complete node member

/-- Registering a task preserves old links and adds only unresolved nodes.
Witness: old-or-new task-node membership; a new empty value cannot require stream links.
-/
theorem State.StoredStreamsComplete.addTask {queue : State} {work omitted}
    (complete : queue.StoredStreamsComplete work omitted) (task : Task)
    : (queue.addTask task).StoredStreamsComplete work omitted := by
  intro node member stored
  rcases queue.addTask_startedOldOrNew task member with old | new
  · exact complete node old stored
  · subst node; cases stored

/-- Appending child-stream links cannot lose an already required link.
Witness: only the selected producer is replaced, with its existing list as a prefix.
-/
theorem State.StoredStreamsComplete.addStreams {queue : State} {work omitted}
    (complete : queue.StoredStreamsComplete work omitted) (streams : List Stream)
    (parent : Option Occurrence)
    : (queue.addStreams streams parent).1.StoredStreamsComplete work omitted := by
  cases parent with
  | none => exact complete
  | some occurrence =>
      simp only [State.addStreams]
      split
      · exact complete
      · rename_i node found
        apply complete.putTaskNode
        intro stored included stream dependencies known
        exact List.mem_append_left _
          (complete node (State.taskNode?_some found).1 stored included stream dependencies known)

private theorem fold_preserves {α β : Type} (property : α → Prop) (step : α → β → α)
    (preserved : ∀ current item, property current → property (step current item))
    (items : List β) (current : α) (prior : property current)
    : property (items.foldl step current) := by
  induction items generalizing current with
  | nil => exact prior
  | cons item rest ih => exact ih _ (preserved current item prior)

/-- Immediate work integration retains complete links on all earlier stored producers.
Witness: group registration, unresolved task creation, and link extension preserve coverage.
-/
theorem State.StoredStreamsComplete.maybeIntegrateWork {queue : State} {work omitted}
    (complete : queue.StoredStreamsComplete work omitted) (chunk : Work)
    (parent : Option Occurrence := none)
    : (queue.maybeIntegrateWork chunk parent).1.StoredStreamsComplete work omitted := by
  have tasks := fold_preserves (fun current => current.StoredStreamsComplete work omitted)
    State.addTask (fun _ task prior => prior.addTask task) chunk.tasks _
    (complete.addGroups chunk.groups)
  exact tasks.addStreams chunk.streams parent

-----------------------------------------------------------------------------------------
-- Attaching a fresh success discharges the temporary preparation exception
-----------------------------------------------------------------------------------------

/-- Fresh complete stream inputs restore coverage for the temporarily exempted producer.
Witness: all required keys survive selection; replacement updates every matching raw node,
while each nonmatching node was already covered. Task-map uniqueness is unnecessary.
-/
theorem State.StoredStreamsComplete.attachProducer {queue : State} {work occurrence node}
    (complete : queue.StoredStreamsComplete work (some occurrence))
    (found : queue.taskNode? occurrence = some node) (streams : List Stream)
    (supplied
      : ∀ stream dependencies,
          NodeAt work stream .stream dependencies (some occurrence)
          → (⟨stream⟩ : Stream) ∈ streams)
    (fresh : ∀ stream ∈ streams, queue.stream? stream.node.key = none)
    : (queue.addStreams streams (some occurrence)).1.StoredStreamsComplete work := by
  have identity := (State.taskNode?_some found).2
  unfold State.addStreams
  dsimp only
  split
  · rename_i missing
    cases found.symm.trans missing
  · rename_i current lookup
    have same : current = node := Option.some.inj (lookup.symm.trans found)
    subst current
    intro candidate member stored _ stream dependencies known
    obtain ⟨old, included, equal⟩ := List.mem_map.mp member
    split at equal
    · subst candidate
      have required := supplied stream dependencies (identity ▸ known)
      exact List.mem_append_right _
        (queue.addStreams_selection_covers streams required (fresh ⟨stream⟩ required))
    · rename_i other
      subst candidate
      apply complete old included stored _ stream dependencies known
      intro same
      apply other
      apply (occurrence_beq_iff_eq _ _).mpr
      exact (Option.some.inj same).symm.trans identity.symm

/-- Preparing a matched fresh object success establishes complete links for every stored task.
Witness: install the value with one temporary exception, preserve all other links through
registration, then attach every structural child stream and remove that exception.
-/
theorem State.StoredStreamsComplete.integrateSuccess {queue : State}
    {work occurrence node result} (complete : queue.StoredStreamsComplete work)
    (found : queue.taskNode? occurrence = some node)
    (matching : (GraphEvent.taskSuccess occurrence result).MatchesWork work)
    (fresh : ∀ stream ∈ result.work.streams, queue.stream? stream.node.key = none)
    : ((queue.putTaskNode { node with value := some result.value }).maybeIntegrateWork
        result.work (some occurrence)).1.StoredStreamsComplete
        work := by
  let stored := queue.putTaskNode { node with value := some result.value }
  let grouped := (stored.addGroups result.work.groups).1
  have installed : stored.StoredStreamsComplete work (some occurrence) := by
    apply (complete.except occurrence).putTaskNode
    intro _ included
    exact False.elim (included (congrArg some (State.taskNode?_some found).2.symm))
  have groupedLookup : grouped.taskNode? occurrence =
      some { node with value := some result.value } := by
    change grouped.taskNodes.find? _ = _
    rw [State.addGroups_taskNodes]
    exact State.putTaskNode_value_lookup found _
  have integrated := fold_preserves
    (fun current : State => current.StoredStreamsComplete work (some occurrence)
      ∧ current.taskNode? occurrence = some { node with value := some result.value })
    State.addTask
    (fun _ task prior => ⟨prior.1.addTask task, State.addTask_taskNode?_of_some prior.2 task⟩)
    result.work.tasks grouped ⟨installed.addGroups _, groupedLookup⟩
  apply integrated.1.attachProducer integrated.2 result.work.streams
  · exact fun _ _ known => matching.taskChildStreams_complete known
  · intro stream member
    simpa only [State.stream?, fold_projection State.streams State.addTask State.addTask_streams,
      grouped, State.addGroups_streams, stored, State.putTaskNode] using fresh stream member

end GraphQL.IncrementalDelivery.ReferenceWorkQueue
