import Proofs.GraphQL.IncrementalDelivery.WorkQueueImplementation.TaskRegistrationCoverage
import Proofs.GraphQL.IncrementalDelivery.WorkQueueImplementation.StreamRegistrationCoverage

/-! Every structural stream is supplied at its exact producer's registration boundary. -/

namespace GraphQL.IncrementalDelivery.ReferenceWorkQueue
open GraphQL.IncrementalDelivery.WorkQueueSemantics

-----------------------------------------------------------------------------------------
-- Inverse lowering follows combine edges but stops at each producer boundary
-----------------------------------------------------------------------------------------

/-- Immediate streams belong to the existing chunk selected by their structural producer.
Witness: combine edges preserve inclusion; object/item edges select the exact child chunk.
`located` fixes the subtree and its producer without any generated-work assumption.
-/
theorem Located.streamRegistrationWork {root address current producer enclosing}
    (located : Located root address current producer enclosing)
    : ∃ chunk,
        taskRegistrationWork? root producer = some chunk
        ∧ (Work.fromExecution current address).streams.Subset chunk.streams := by
  have navigation := StructuralEquivalence.located_of_current located
  clear located
  induction navigation with
  | root => exact ⟨_, rfl, List.Subset.refl _⟩
  | left _ ih =>
      obtain ⟨chunk, same, included⟩ := ih
      exact ⟨chunk, same, (List.subset_append_left _ _).trans included⟩
  | right _ ih =>
      obtain ⟨chunk, same, included⟩ := ih
      exact ⟨chunk, same, (List.subset_append_right _ _).trans included⟩
  | executionGroup prior _ =>
      refine ⟨_, ?_, List.Subset.refl _⟩
      have found := prior.toCurrent
      unfold WorkQueueSemantics.Located at found
      simp [taskRegistrationWork?, taskChildWork?, found]
  | item prior entry _ =>
      refine ⟨_, ?_, List.Subset.refl _⟩
      have found := prior.toCurrent
      unfold WorkQueueSemantics.Located at found
      simp [taskRegistrationWork?, streamItemWork?, found, entry]

/-- Every stream descriptor occurs in the chunk installed at its producer boundary.
Witness: inverse immediate lowering includes the singleton structural stream descriptor.
-/
theorem NodeAt.stream_registrationWork {work node dependencies producer}
    (known : NodeAt work node .stream dependencies producer)
    : ∃ chunk,
        taskRegistrationWork? work producer = some chunk
        ∧ (⟨node⟩ : Stream) ∈ chunk.streams := by
  obtain ⟨address, items, located⟩ := known
  obtain ⟨chunk, boundary, included⟩ := Located.streamRegistrationWork located
  exact ⟨chunk, boundary, included List.mem_cons_self⟩

/-- Every producer-free structural stream is supplied by root lowering.
Witness: its producer selects the root chunk, including zero-item streams.
-/
theorem NodeAt.stream_initial_input {work node dependencies}
    (known : NodeAt work node .stream dependencies none)
    : (⟨node⟩ : Stream) ∈ (Work.fromExecution work).streams := by
  obtain ⟨chunk, boundary, member⟩ := NodeAt.stream_registrationWork known
  exact (Option.some.inj boundary) ▸ member

/-- A matched object success supplies every structural stream generated by that object.
Witness: source matching identifies the same child chunk as inverse structural lowering.
This does not assume the queue accepts or publishes that success.
-/
theorem GraphEvent.MatchesWork.taskChildStreams_complete {work producer result}
    (matching : (GraphEvent.taskSuccess producer result).MatchesWork work)
    {node dependencies} (known : NodeAt work node .stream dependencies (some producer))
    : (⟨node⟩ : Stream) ∈ result.work.streams := by
  obtain ⟨chunk, boundary, member⟩ := NodeAt.stream_registrationWork known
  obtain ⟨_, _, _, _, children⟩ := matching
  cases producer with
  | item address index => cases children
  | executionGroup address =>
      exact (Option.some.inj (boundary.symm.trans children)) ▸ member

/-- A matched stream item supplies every structural stream generated by that item.
Witness: the exact ordinal's child-work equation identifies its registration chunk.
-/
theorem GraphEvent.MatchesWork.itemChildStreams_complete {work stream items}
    (matching : (GraphEvent.streamItems stream items).MatchesWork work)
    {item : StreamItem} (selected : item ∈ items) {node dependencies}
    (known : NodeAt work node .stream dependencies (some item.occurrence))
    : (⟨node⟩ : Stream) ∈ item.work.streams := by
  obtain ⟨chunk, boundary, member⟩ := NodeAt.stream_registrationWork known
  obtain ⟨_, _, _, children⟩ := matching item selected
  cases identity : item.occurrence with
  | executionGroup address => simp [streamItemWork?, identity] at children
  | item address index =>
      rw [identity] at boundary children
      exact (Option.some.inj (boundary.symm.trans children)) ▸ member

end GraphQL.IncrementalDelivery.ReferenceWorkQueue
