import Proofs.GraphQL.IncrementalDelivery.WorkQueueImplementation.RegisteredCarrierCoverage
import Proofs.GraphQL.IncrementalDelivery.WorkQueueImplementation.StructuralRetiredRegistration

/-! Successful group carriers cover every structural object contributor. -/

namespace GraphQL.IncrementalDelivery.ReferenceWorkQueue
open GraphQL.IncrementalDelivery.Execution (WorkQueueEvent)
open GraphQL.IncrementalDelivery.WorkQueueSemantics

-----------------------------------------------------------------------------------------
-- Actual successful carriers need no supplied registration or storage premise
-----------------------------------------------------------------------------------------

/-- Every structural object contributor is registered by its successful group's carrier.
Witness: actual handler replay retires the group healthy; producer-rank induction then
recovers registration, including tasks generated by earlier object and stream-item inputs.
-/
theorem ExecutedWork.successfulCarrier_structuralContributor_registered
    {work before event group groups streams address owners producer payload}
    (generated : ExecutedWork work)
    (valid : ValidGraphEvents work (before ++ [event]))
    (started
      : (State.initialize (Work.fromExecution work)).acceptsBatch (before ++ [event])
        = true)
    (carrier
      : Execution.WorkQueueEvent.groupSuccess group groups streams
        ∈ (((State.initialize (Work.fromExecution work)).replayGraphEvents
              before).handleGraphEvent
            event).2)
    (known : TaskAt work (.executionGroup address) owners producer payload)
    (contributes : group.ref ∈ owners)
    : ∃ task ∈
        ((State.initialize (Work.fromExecution work)).replayGraphEvents
          (before ++ [event])).tasks,
        task.occurrence = .executionGroup address
        ∧ task.groups.map Execution.DeliveryNode.ref = owners := by
  obtain ⟨_, _, retired, healthy, _⟩ :=
    generated.replayGraphEvents_successfulCarrier_retiredHealthy valid
      (State.acceptsBatch_prefix started) carrier
  exact generated.retired_structuralContributor_registered valid started known contributes
    retired healthy

/-- All structural object contributors publish strictly before a successful group carrier.
Witness: derive registration from healthy retirement and apply registered coverage on the
same supplied replay ledger. The strict prefix includes earlier handlers and only outputs
before this carrier within its handler; neither batching nor a new matching is chosen.
-/
theorem ExecutedWork.successfulCarrier_structuralContributor_covered
    {work before event index group groups streams address owners producer payload
      published}
    (generated : ExecutedWork work)
    (valid : ValidGraphEvents work (before ++ [event]))
    (started
      : (State.initialize (Work.fromExecution work)).acceptsBatch (before ++ [event])
        = true)
    (covered
      : (State.initialize (Work.fromExecution work)).ReplayClosuresCovered
          (before ++ [event]) published)
    (carrier
      : (((State.initialize (Work.fromExecution work)).replayGraphEvents
            before).handleGraphEvent
          event).2[index]?
        = some (.groupSuccess group groups streams))
    (known : TaskAt work (.executionGroup address) owners producer payload)
    (contributes : group.ref ∈ owners)
    : ∃ value,
        (Occurrence.executionGroup address, value)
        ∈ published.take
            ((((State.initialize (Work.fromExecution work)).rawEventReplay
                before).2.flatMap
                WorkQueueEvent.objectValues).length
              + (((((State.initialize (Work.fromExecution work)).replayGraphEvents
                      before).handleGraphEvent
                    event).2.take
                    index).flatMap
                  WorkQueueEvent.objectValues).length) := by
  obtain ⟨task, registered, occurrence, groups⟩ :=
    generated.successfulCarrier_structuralContributor_registered valid started
      (List.mem_of_getElem? carrier) known contributes
  simpa only [occurrence]
    using generated.successfulCarrier_registeredContributor_covered valid started covered
      carrier registered (groups.symm ▸ contributes)

end GraphQL.IncrementalDelivery.ReferenceWorkQueue
