import Proofs.GraphQL.IncrementalDelivery.WorkQueueImplementation.ItemPublicationReflection
import Proofs.GraphQL.IncrementalDelivery.WorkQueueImplementation.TerminalRegisteredTasks
import Proofs.GraphQL.IncrementalDelivery.WorkQueueImplementation.FullControlAdmission

/-! A published item exposes all its immediate child nodes to concrete terminal accounting. -/

namespace GraphQL.IncrementalDelivery.ReferenceWorkQueue.ConformancePlan
open GraphQL.IncrementalDelivery.WorkQueueSemantics

-----------------------------------------------------------------------------------------
-- Published item producers discharge the registration premise for their object children
-----------------------------------------------------------------------------------------

/-- Every object task generated by a published item is accounted at actual termination.
Witness: reflect the publication to the successful input, derive permanent child
registration, then apply registered-task accounting on the same matching and cuts.
-/
theorem terminal_itemProducedTask_accounted
    {work inputs w address owners payload source index} (generated : ExecutedWork work)
    (valid : ValidGraphEvents work inputs.flatten)
    (started : inputsStarted work inputs = true)
    (history : w.events = (initialQueue work).nonterminalAtoms inputs)
    (admitted : PublicationAdmission work w)
    (ledger : BufferedClosureLedger work inputs w)
    (explained
      : Explains work (initialQueue work).initialGroups
          (initialQueue work).initialStreams w.events w.matching w.failures)
    (visible
      : ((initialQueue work).objectFailureContributions inputs.flatten).Subset
          (failedBefore w.failures w.events.length))
    (ended : ((initialQueue work).runNormalized inputs).1.terminated = true)
    (known
      : TaskAt work (.executionGroup address) owners (some (.item source index)) payload)
    (published : Published w.matching w.events (.item source index))
    : TaskAccounted work w.matching w.events w.failures (.executionGroup address) := by
  have accepted : (initialQueue work).batchesStarted inputs = true := by
    rwa [← inputsStarted_eq_batchesStarted]
  obtain ⟨task, member, identity, _⟩ :=
    TaskAt.executionGroup_registered_of_itemSuccess known valid
      ((initialQueue work).batchesStarted_acceptsBatch inputs accepted)
      (published_item_success valid started history admitted ledger published)
  exact identity
  ▸ terminal_registeredTask_accounted generated valid started history ledger
      explained visible ended member

/-- A group generated by a published item is failed or fully accounted at termination.
Witness: its structural contributing object task is registered by the actual item handler;
terminal contributor accounting also covers every other structural contributor to the ref.
-/
theorem terminal_itemProducedGroup_accounted
    {work inputs w group dependencies source index} (generated : ExecutedWork work)
    (valid : ValidGraphEvents work inputs.flatten)
    (started : inputsStarted work inputs = true)
    (history : w.events = (initialQueue work).nonterminalAtoms inputs)
    (admitted : PublicationAdmission work w)
    (ledger : BufferedClosureLedger work inputs w)
    (explained
      : Explains work (initialQueue work).initialGroups
          (initialQueue work).initialStreams w.events w.matching w.failures)
    (visible
      : ((initialQueue work).objectFailureContributions inputs.flatten).Subset
          (failedBefore w.failures w.events.length))
    (ended : ((initialQueue work).runNormalized inputs).1.terminated = true)
    (known : NodeAt work group .group dependencies (some (.item source index)))
    (published : Published w.matching w.events (.item source index))
    : NodeFailed work w.matching w.events w.failures group.ref
      ∨ NodeAccounted work w.matching w.events w.failures group.ref := by
  have accepted : (initialQueue work).batchesStarted inputs = true := by
    rwa [← inputsStarted_eq_batchesStarted]
  have success := published_item_success valid started history admitted ledger published
  obtain ⟨occurrence, owners, payload, task, contributes⟩ := known.group_task
  cases occurrence with
  | executionGroup address =>
      obtain ⟨candidate, member, _, groups⟩ :=
        TaskAt.executionGroup_registered_of_itemSuccess task valid
          ((initialQueue work).batchesStarted_acceptsBatch inputs accepted) success
      exact terminal_registeredContributor_groupAccounted generated valid started history ledger
        explained visible ended known member (groups.symm ▸ contributes)
  | item address ordinal =>
      obtain ⟨stream, entries, enclosing, result, children, located, entry, sameOwners,
        samePayload⟩ := task
      rw [sameOwners] at contributes
      exact False.elim (generated.groupStreamRefsDisjoint known (.stream located)
        (List.mem_singleton.mp contributes))

-----------------------------------------------------------------------------------------
-- Item-produced groups and streams satisfy the exact node-accounting alternative
-----------------------------------------------------------------------------------------

/-- Every stream generated by a published item completes at actual termination.
Witness: publication reflection supplies its successful input, after which complete notice
coverage and concrete stream tracking force closure on the unchanged canonical history.
-/
theorem terminal_itemProducedStream_of_publication
    {work inputs w node dependencies source index} (generated : ExecutedWork work)
    (valid : ValidGraphEvents work inputs.flatten)
    (started : inputsStarted work inputs = true)
    (history : w.events = (initialQueue work).nonterminalAtoms inputs)
    (admitted : PublicationAdmission work w)
    (ledger : BufferedClosureLedger work inputs w)
    (ended : ((initialQueue work).runNormalized inputs).1.terminated = true)
    (known : NodeAt work node .stream dependencies (some (.item source index)))
    (published : Published w.matching w.events (.item source index))
    : node.ref ∈ completedRefs w.events :=
  terminal_itemProducedStream_completed generated valid started history ended known
    (published_item_success valid started history admitted ledger published)

/-- Every node whose producing item was published satisfies the terminal node clause.
Witness: complete stream closure or registered-group accounting, with announced groups
closed by concrete tracking. Recursive accounting need only supply the producer publication.
-/
theorem terminal_itemProducedNode_accounted
    {work inputs w node kind dependencies source index} (generated : ExecutedWork work)
    (valid : ValidGraphEvents work inputs.flatten)
    (started : inputsStarted work inputs = true)
    (history : w.events = (initialQueue work).nonterminalAtoms inputs)
    (admitted : PublicationAdmission work w)
    (ledger : BufferedClosureLedger work inputs w)
    (explained
      : Explains work (initialQueue work).initialGroups
          (initialQueue work).initialStreams w.events w.matching w.failures)
    (visible
      : ((initialQueue work).objectFailureContributions inputs.flatten).Subset
          (failedBefore w.failures w.events.length))
    (ended : ((initialQueue work).runNormalized inputs).1.terminated = true)
    (known : NodeAt work node kind dependencies (some (.item source index)))
    (published : Published w.matching w.events (.item source index))
    : node.ref ∈ completedRefs w.events
      ∨ node.ref ∉ announcedRefs (initialRefs work) w.events
        ∧ (NodeFailed work w.matching w.events w.failures node.ref
            ∨ NodeAccounted work w.matching w.events w.failures node.ref) := by
  cases kind with
  | stream =>
      exact .inl (terminal_itemProducedStream_of_publication generated valid started
        history admitted ledger ended known published)
  | group =>
      classical
      by_cases announced : node.ref ∈ announcedRefs (initialRefs work) w.events
      · exact .inl (announced_terminalCompleted generated valid started history ended announced)
      · exact .inr ⟨announced, terminal_itemProducedGroup_accounted generated valid started
          history admitted ledger explained visible ended known published⟩

/-- The full admission witness accounts for every node generated by a published item.
Witness: keep the existing matching, closure ledger, and failure cuts; derive endpoint
failure visibility and apply item-publication reflection to each structural child.
-/
theorem mixed_itemTerminalCertificates {work inputs}
    (premises : ReplayPremises work inputs)
    : ∃ w : Witness,
        w.events = (initialQueue work).nonterminalAtoms inputs
        ∧ BatchShape work inputs w
        ∧ AnnouncedFailures work w
        ∧ UncancelledFailures work w
        ∧ PublicationAdmission work w
        ∧ ControlAdmission work w
        ∧ Explains work (initialQueue work).initialGroups
            (initialQueue work).initialStreams w.events w.matching w.failures
        ∧ (((initialQueue work).runNormalized inputs).1.terminated = true
            → ∀ node kind dependencies address index,
                NodeAt work node kind dependencies (some (.item address index))
                → Published w.matching w.events (.item address index)
                → node.ref ∈ completedRefs w.events
                  ∨ node.ref ∉ announcedRefs (initialRefs work) w.events
                    ∧ (NodeFailed work w.matching w.events w.failures node.ref
                        ∨ NodeAccounted work w.matching w.events w.failures
                            node.ref)) := by
  obtain ⟨w, history, shape, announced, uncancelled, publications, controls, _, _, _, _, _,
    ledger, _, _, _, _, _, streams, _, exactCuts⟩ :=
    mixed_admissionCertificates premises.generated premises.valid premises.started
  have explained := explains premises.initialized announced uncancelled publications controls
  have partition := exactCuts ▸ mergeFailureCuts_partition _ streams
  have visible := objectFailureContributions_visible premises.started announced.1 partition
  exact ⟨w, history, shape, announced, uncancelled, publications, controls, explained,
    fun ended _ _ _ _ _ known published => terminal_itemProducedNode_accounted
      premises.generated premises.valid premises.started history publications ledger explained
      visible ended known published⟩

end GraphQL.IncrementalDelivery.ReferenceWorkQueue.ConformancePlan
