import Proofs.GraphQL.IncrementalDelivery.WorkQueueImplementation.ObjectPublicationAcceptance
import Proofs.GraphQL.IncrementalDelivery.WorkQueueImplementation.TerminalItemProducedNodes

/-! Published object producers register all their child tasks and contributing groups. -/

namespace GraphQL.IncrementalDelivery.ReferenceWorkQueue.ConformancePlan
open GraphQL.IncrementalDelivery.WorkQueueSemantics

-----------------------------------------------------------------------------------------
-- Reflect a published structural object to its concrete accepted source boundary
-----------------------------------------------------------------------------------------

/-- A published structural object has an accepted, source-matched storing boundary.
Witness: publication provenance selects its object atom, then exact raw release accounting
recovers the actual input, lookup, and healthy-owner guard for that same occurrence.
-/
theorem published_object_processed {work inputs w address}
    (generated : ExecutedWork work) (valid : ValidGraphEvents work inputs.flatten)
    (started : inputsStarted work inputs = true)
    (history : w.events = (initialQueue work).nonterminalAtoms inputs)
    (admitted : PublicationAdmission work w)
    (ledger : BufferedClosureLedger work inputs w)
    (published : Published w.matching w.events (.executionGroup address))
    : ∃ before result after node,
        inputs.flatten = before ++ .taskSuccess (.executionGroup address) result :: after
        ∧ (GraphEvent.taskSuccess (.executionGroup address) result).MatchesWork work
        ∧ ((initialQueue work).replayGraphEvents before).taskNode?
            (.executionGroup address)
          = some node
        ∧ ((initialQueue work).replayGraphEvents before).taskHasHealthyOwner node.task
          = true := by
  obtain ⟨index, event, selected, value, same⟩ := published
  have exactValue := same ▸ admitted.publicationAt selected value
  cases event <;> try cases value
  case groupValues owner payload =>
    simpa only [same] using Witness.groupPublication_processed generated valid started
      history ledger selected
  case streamValues node values groups streams =>
    cases values with
    | nil => cases exactValue
    | cons head tail =>
        cases tail with
        | cons next rest => cases exactValue
        | nil =>
            obtain ⟨owners, producer, impossible⟩ := exactValue
            obtain ⟨_, _, _, _, _, _, _, _, payload⟩ := impossible

/-- Every object child of a published object is permanently registered.
Witness: the actual accepted handler integrates its source-matched child chunk; subsequent
handlers preserve the task registry. No endpoint lookup or child publication is assumed.
-/
theorem published_object_child_registered {work inputs w address owners producer payload}
    (generated : ExecutedWork work) (valid : ValidGraphEvents work inputs.flatten)
    (started : inputsStarted work inputs = true)
    (history : w.events = (initialQueue work).nonterminalAtoms inputs)
    (admitted : PublicationAdmission work w)
    (ledger : BufferedClosureLedger work inputs w)
    (known
      : TaskAt work (.executionGroup address) owners
          (some (.executionGroup producer)) payload)
    (published : Published w.matching w.events (.executionGroup producer))
    : ∃ task ∈ ((initialQueue work).replayGraphEvents inputs.flatten).tasks,
        task.occurrence = .executionGroup address
        ∧ task.groups.map Execution.DeliveryNode.ref = owners := by
  obtain ⟨before, result, after, node, sourceEq, matching, found, healthy⟩ :=
    published_object_processed generated valid started history admitted ledger published
  exact TaskAt.executionGroup_registered_after_object known matching
    ⟨after, by simp only [sourceEq, List.append_assoc, List.singleton_append]⟩ found
    healthy

-----------------------------------------------------------------------------------------
-- Terminal registration accounting covers all object-produced groups and object tasks
-----------------------------------------------------------------------------------------

/-- Every object task generated by a published object is accounted at termination.
Witness: complete child registration followed by the existing registered-task theorem,
using the unchanged matching and visible failure-cut inventory.
-/
theorem terminal_objectProducedTask_accounted
    {work inputs w address owners payload producer} (generated : ExecutedWork work)
    (valid : ValidGraphEvents work inputs.flatten)
    (started : inputsStarted work inputs = true)
    (history : w.events = (initialQueue work).nonterminalAtoms inputs)
    (admitted : PublicationAdmission work w)
    (ledger : BufferedClosureLedger work inputs w)
    (explained
      : Explains work (initialQueue work).initialGroups
          (initialQueue work).initialStreams w.events w.matching w.failures)
    (visible
      : ((initialQueue work).objectFailureContributions inputs.flatten).Subset
          (failedBefore w.failures w.events.length))
    (ended : ((initialQueue work).runNormalized inputs).1.terminated = true)
    (known
      : TaskAt work (.executionGroup address) owners
          (some (.executionGroup producer)) payload)
    (published : Published w.matching w.events (.executionGroup producer))
    : TaskAccounted work w.matching w.events w.failures (.executionGroup address) := by
  obtain ⟨task, member, identity, _⟩ := published_object_child_registered generated valid
    started history admitted ledger known published
  exact identity ▸ terminal_registeredTask_accounted generated valid started history ledger
    explained visible ended member

/-- Every group generated by a published object is failed or fully accounted at termination.
Witness: one structural contributing object task is registered by that producer's actual
success handler; terminal contributor accounting covers all contributors to the group ref.
-/
theorem terminal_objectProducedGroup_accounted {work inputs w group dependencies producer}
    (generated : ExecutedWork work) (valid : ValidGraphEvents work inputs.flatten)
    (started : inputsStarted work inputs = true)
    (history : w.events = (initialQueue work).nonterminalAtoms inputs)
    (admitted : PublicationAdmission work w)
    (ledger : BufferedClosureLedger work inputs w)
    (explained
      : Explains work (initialQueue work).initialGroups
          (initialQueue work).initialStreams w.events w.matching w.failures)
    (visible
      : ((initialQueue work).objectFailureContributions inputs.flatten).Subset
          (failedBefore w.failures w.events.length))
    (ended : ((initialQueue work).runNormalized inputs).1.terminated = true)
    (known : NodeAt work group .group dependencies (some (.executionGroup producer)))
    (published : Published w.matching w.events (.executionGroup producer))
    : NodeFailed work w.matching w.events w.failures group.ref
      ∨ NodeAccounted work w.matching w.events w.failures group.ref := by
  obtain ⟨occurrence, owners, payload, task, contributes⟩ := known.group_task
  cases occurrence with
  | executionGroup address =>
      obtain ⟨candidate, member, _, groups⟩ := published_object_child_registered generated valid
        started history admitted ledger task published
      exact terminal_registeredContributor_groupAccounted generated valid started history ledger
        explained visible ended known member (groups.symm ▸ contributes)
  | item address ordinal =>
      obtain ⟨stream, entries, enclosing, result, children, located, entry, sameOwners,
        samePayload⟩ := task
      rw [sameOwners] at contributes
      exact False.elim (generated.groupStreamRefsDisjoint known (.stream located)
        (List.mem_singleton.mp contributes))

/-- All groups with absent or published producers share terminal admission accounting.
Witness: retain one full mixed certificate; root groups use initial registration, item
children use publication reflection, and object children use the accepted storing bridge.
-/
theorem mixed_producedGroupTerminalCertificates {work inputs}
    (premises : ReplayPremises work inputs)
    : ∃ w : Witness,
        w.events = (initialQueue work).nonterminalAtoms inputs
        ∧ BatchShape work inputs w
        ∧ AnnouncedFailures work w
        ∧ UncancelledFailures work w
        ∧ PublicationAdmission work w
        ∧ ControlAdmission work w
        ∧ Explains work (initialQueue work).initialGroups
            (initialQueue work).initialStreams w.events w.matching w.failures
        ∧ (((initialQueue work).runNormalized inputs).1.terminated = true
            → ∀ group dependencies producer,
                NodeAt work group .group dependencies producer
                → (∀ occurrence,
                    producer = some occurrence → Published w.matching w.events occurrence)
                → NodeFailed work w.matching w.events w.failures group.ref
                  ∨ NodeAccounted work w.matching w.events w.failures group.ref) := by
  obtain ⟨w, history, shape, announced, uncancelled, publications, controls, _, _, _, _, _,
    ledger, _, _, _, _, _, streams, _, exactCuts⟩ :=
    mixed_admissionCertificates premises.generated premises.valid premises.started
  have explained := explains premises.initialized announced uncancelled publications controls
  have partition := exactCuts ▸ mergeFailureCuts_partition _ streams
  have visible := objectFailureContributions_visible premises.started announced.1 partition
  refine ⟨
    w,
    history,
    shape,
    announced,
    uncancelled,
    publications,
    controls,
    explained,
    ?_
  ⟩
  intro ended group dependencies producer known available
  cases producer with
  | none =>
      exact terminal_rootGroup_accounted premises.generated premises.valid
        premises.started history ledger explained visible ended known
  | some occurrence =>
      cases occurrence with
      | executionGroup address =>
          exact terminal_objectProducedGroup_accounted premises.generated premises.valid
            premises.started history publications ledger explained visible ended known
            (available _ rfl)
      | item address index =>
          exact terminal_itemProducedGroup_accounted premises.generated premises.valid
            premises.started history publications ledger explained visible ended known
            (available _ rfl)

end GraphQL.IncrementalDelivery.ReferenceWorkQueue.ConformancePlan
