/- Generated by conformance/scripts/gen-graphql-js-conformance.mjs. -/
import Tests.Conformance.Execution.Common
import GraphQL.NamedFragment.Execution

namespace GraphQL
namespace Tests
namespace Conformance
namespace NamedFragment
namespace GraphQLJS

-- Source: src/execution/__tests__/fragments-test.ts
def named_fragment_basic_spreadSchema : GraphQL.Schema :=
  {
    queryType := "Query",
    types :=
      [
        .object
          {
            name := "Query",
            fields :=
              [{ name := "hero", outputType := .named "Character", arguments := [] }],
            interfaces := []
          },
        .object
          {
            name := "Character",
            fields :=
              [{ name := "name", outputType := .named "String", arguments := [] }],
            interfaces := []
          }
      ]
  }

def named_fragment_basic_spreadOperation : GraphQL.NamedFragment.Operation :=
  {
    name := none,
    variableDefinitions :=
      [],
    fragmentDefinitions :=
      [{
        name := "NameFragment"
        typeCondition := "Character"
        selectionSet :=
          [.field "name" "name" [] [] []]
      }],
    selectionSet :=
      [.field "hero" "hero" [] [] [.fragmentSpread "NameFragment" []]]
  }

def named_fragment_basic_spreadVariables : GraphQL.Execution.VariableValues :=
  []

def named_fragment_basic_spreadSource : GraphQL.Execution.ResolverValue String :=
  .object "Query" "root"

def named_fragment_basic_spreadResolvers : GraphQL.Execution.Resolvers String :=
  {
    resolve :=
      fun parentType fieldName _arguments source =>
        match parentType, fieldName, source with
        | "Query", "hero", .object _ "root" => some (.object "Character" "hero")
        | "Character", "name", .object _ "hero" => some (.scalar "Leia")
        | _, _, _ => some .null
    resolve_argumentsEquivalent := by
      intros
      rfl
  }

def named_fragment_basic_spreadExpectedData : GraphQL.Execution.ResponseValue :=
  .object ([("hero", .object ([("name", .scalar "Leia")]))])

theorem named_fragment_basic_spread_matches_graphql_js_projection
    : let response :=
        GraphQL.NamedFragment.Execution.executeQueryWithFuel
          named_fragment_basic_spreadSchema named_fragment_basic_spreadResolvers
          named_fragment_basic_spreadVariables named_fragment_basic_spreadOperation 100
          named_fragment_basic_spreadSource
      response.errors = 0
      ∧ GraphQL.Tests.Conformance.Execution.responseEqBool response.data
          named_fragment_basic_spreadExpectedData
        = true := by
  native_decide

end GraphQLJS
end NamedFragment
end Conformance
end Tests
end GraphQL
