import Proofs.GraphQL.IncrementalDelivery.WorkQueueImplementation.ExposedGroupCausality
import Proofs.GraphQL.IncrementalDelivery.WorkQueueImplementation.RootItemCertificates
import Proofs.GraphQL.IncrementalDelivery.WorkQueueImplementation.MixedFailureWitness
import Proofs.GraphQL.IncrementalDelivery.WorkQueueImplementation.ProducedTaskRegistration
import Tests.GraphQL.IncrementalDelivery.Execution

/-! A published item protects deferred child work from a later failure of its stream. -/

namespace GraphQL.IncrementalDelivery.Tests.WorkSchedulerItemBoundary
open GraphQL.IncrementalDelivery.Execution
open GraphQL.IncrementalDelivery.ReferenceWorkQueue
open GraphQL.IncrementalDelivery.WorkQueueSemantics

private def modelSchema : Schema :=
  {
    queryType := "Query",
    types :=
      [
        .object
          {
            name := "Query",
            fields :=
              [{ name := "users", outputType := .list (.nonNull (.named "User")) }]
          },
        .object
          {
            name := "User",
            fields := [{ name := "required", outputType := .nonNull (.named "String") }]
          }
      ]
  }

private def modelResolvers : Resolvers Nat :=
  {
    resolve :=
      fun _ field _ _ =>
        if field = "users" then some (.list [.object "User" 0, .null]) else none,
    resolve_argumentsEquivalent := by intros; rfl
  }

private def selections : List Selection :=
  [field "users" [defer [field "required"] (some "C")]
    [.stream (.boolean true) none (.int 0)]]

private def work : Execution.Work :=
  ((executeRootSelectionSetCore modelSchema modelResolvers [] 30 "Query"
      (.object "Query" 0) selections).run
    0).1.work

private def stream : DeliveryNode := { ref := 0, path := [.field "users"] }

private def child : DeliveryNode :=
  { ref := 1, path := [.field "users", .index 0], label := some (.string "C") }

private def firstItem : Occurrence := .item [0, 0, 1] 0
private def failedItem : Occurrence := .item [0, 0, 1] 1
private def childTask : Occurrence := .executionGroup [0, 0, 1, 0, 1, 0]

private def children : Execution.Work :=
  .combine .empty
    (.combine (.executionGroup [⟨child, []⟩] child.path (.error 1) .empty) .empty)

private def item : StreamItem :=
  ⟨firstItem, ⟨.object [], 0⟩, Work.fromExecution children [0, 0, 1, 0]⟩

private def received : List GraphEvent :=
  [.streamItems stream [item], .streamFailure stream 1]

private def events : List WorkQueueEvent :=
  [.streamValues stream [⟨.object [], 0⟩] [child] [], .streamFailure stream 1]

private def cuts : FailureCuts := [(1, failedItem)]
private def matching : PublicationMatching := fun _ => firstItem

/-- The mixed item/child fixture is generated by finite pure query execution.
Witness: the defining root equation, with a non-null second list item that fails.
-/
theorem generated : ExecutedWork work :=
  ⟨Nat, modelSchema, modelResolvers, [], 30, "Query", .object "Query" 0, selections, rfl⟩

private theorem stream_located
    : Located work [0, 0, 1]
        (.stream stream [(.ok (.object [], 0), children), (.error 1, .empty)]) none
        [] := by cbv

private theorem first_known
    : TaskAt work firstItem [stream.ref] none (.item stream (.ok (.object [], 0))) :=
  .item stream_located rfl

private theorem failed_known
    : TaskAt work failedItem [stream.ref] none (.item stream (.error 1)) :=
  .item stream_located rfl

private theorem child_known
    : TaskAt work childTask [child.ref] (some firstItem)
        (.object child.path (.error 1)) :=
  .executionGroup (groups := [⟨child, []⟩]) (children := .empty) (owners := []) (by cbv)

private theorem child_node : NodeAt work child .group [] (some firstItem) :=
  ⟨
    [0, 0, 1, 0, 1, 0],
    [⟨child, []⟩],
    child.path,
    .error 1,
    .empty,
    [],
    ⟨child, []⟩,
    by cbv,
    List.mem_cons_self,
    rfl,
    rfl
  ⟩

/-- The two source events obey fixed outcomes, ordering, and actual requested starts.
Witness: the first item's value/child work, followed by the next non-null item failure.
-/
theorem source_valid
    : ValidGraphEvents work received ∧ inputsStarted work [received] = true := by
  have first : ValidGraphEvents work [.streamItems stream [item]] := by
    refine .append .nil ?_ ?_ ?_
    · intro entry member
      obtain rfl := List.mem_singleton.mp member
      exact ⟨_, _, first_known, by cbv⟩
    · simp [GraphEvent.Fresh, GraphEvent.identities, item]
    · exact ⟨_, _, _, _, stream_located, by simp, by simp,
        (by intro source impossible; cases impossible), rfl⟩
  refine ⟨.append first ?_ ?_ ?_, by cbv⟩
  · exact ⟨_, _, _, _, stream_located, .empty, by simp⟩
  · simp [GraphEvent.Fresh, GraphEvent.identities, item]
  · exact ⟨_, _, _, _, stream_located,
      (by intro source impossible; cases impossible), .empty, rfl⟩

/-- The actual queue emits the first item and C's notice before closing the failed stream.
Witness: direct normalized replay; C remains active, so there is no terminal marker.
-/
theorem output
    : ((State.initialize (Work.fromExecution work)).runNormalized [received]).2
      = [events] := by
  cbv

/-- The item's deferred task is absent initially but remains registered after stream failure.
Witness: actual item integration supplies the structural descriptor and registry persistence
retains it through the following failure. Registration does not require child settlement.
-/
theorem item_child_registration_boundary
    : (State.initialize (Work.fromExecution work)).tasks = []
      ∧ ∃ task ∈
          ((State.initialize (Work.fromExecution work)).replayGraphEvents received).tasks,
          task.occurrence = childTask
          ∧ task.groups.map DeliveryNode.ref = [child.ref] := by
  refine ⟨by cbv, ?_⟩
  exact TaskAt.executionGroup_registered_of_itemSuccess child_known source_valid.1
    (by cbv) (by simp [received, GraphEvent.successes, item, firstItem])

/-- Registration recovers the successful stream-item boundary without fixture enumeration.
Witness: general region exposure and valid source replay identify C's item producer.
-/
theorem producer_succeeded : firstItem ∈ received.flatMap GraphEvent.successes :=
  generated.registered_group_itemProducer_succeeded source_valid.1 child_node
    (by cbv; exact List.mem_cons_self)

private theorem failed_payloads
    : ∀ cut occurrence,
        (cut, occurrence) ∈ cuts
        → ∃ owners producer payload,
            TaskAt work occurrence owners producer payload
            ∧ payload.failure.isSome = true := by
  intro cut occurrence member
  have same := List.mem_singleton.mp member
  cases same
  exact ⟨_, _, _, failed_known, rfl⟩

/-- The later stream failure cannot cancel the first item in the actual source history.
Witness: general mixed-cut root-item safety, using exact output/source inventories rather
than direct inspection of the cancellation witness's cut.
-/
theorem first_item_safe : ¬TaskCancelled work matching events cuts firstItem := by
  have streamCuts : StreamFailureCuts work events cuts := by
    refine ⟨by cbv, ?_⟩
    intro entry member
    obtain rfl := List.mem_singleton.mp member
    exact ⟨stream, 1, none, rfl, failed_known⟩
  apply streamCuts.rootSourceItem_safe_mixed (objectCuts := [])
    (by simp) (by simp) generated
    (by simp [events, streamAction, StreamAction.Before]) _ source_valid.1 _
    (.stream stream_located) first_known producer_succeeded
  · intro index event selected value
    have bound := (List.getElem?_eq_some_iff.mp selected).1
    have casesIndex : index = 0 ∨ index = 1 := by change index < 2 at bound; omega
    rcases casesIndex with rfl | rfl
    · cases selected
      exact ⟨_, _, first_known⟩
    · cases selected
      cases value
  · intro occurrence member
    have same : occurrence = firstItem := List.mem_singleton.mp member
    exact ⟨0, events[0], rfl, trivial, same.symm⟩

private theorem items_safe
    : ∀ source index,
        Occurrence.item source index ∈ received.flatMap GraphEvent.successes
        → ¬TaskCancelled work matching events cuts (.item source index) := by
  intro source index member
  have same : Occurrence.item source index = firstItem := List.mem_singleton.mp member
  exact same ▸ first_item_safe

/-- The executable group guard now implies full historical health below the stream item.
Witness: the general mixed bridge, genuine item-failure provenance, and first-item safety.
The earlier failure is retained in the cut list rather than discarded from the claim.
-/
theorem child_healthy : ¬NodeFailed work matching events cuts child.ref := by
  apply generated.replayGraphEvents_groupHealthy_of_itemSafety source_valid.1
    (by cbv)
    child_node
    (by cbv; exact List.mem_cons_self)
    (by cbv)
    failed_payloads _ items_safe
  intro occurrence owners producer path result known member
  have same : occurrence = failedItem := List.mem_singleton.mp member
  subst occurrence
  cases StructuralEquivalence.taskAt_of_current known

/-- The pending failed child is not cancelled when the stream fails after its first item.
Witness: the mixed object-cancellation reduction would fail C's proven healthy owner.
-/
theorem child_uncancelled : ¬TaskCancelled work matching events cuts childTask := by
  intro cancelled
  exact child_healthy
    (generated.object_cancelled_owner_failed_of_itemSafety source_valid.1
      failed_payloads items_safe child_known List.mem_cons_self
      (by intro source same; cases same; exact producer_succeeded) cancelled)

-----------------------------------------------------------------------------------------
-- The same canonical witness also handles actual interleaved object and item failures
-----------------------------------------------------------------------------------------

private def mixedReceived : List GraphEvent :=
  [.streamItems stream [item], .taskFailure childTask 1, .streamFailure stream 1]

private def mixedEvents : List WorkQueueEvent :=
  [
    .streamValues stream [⟨.object [], 0⟩] [child] [],
    .groupFailure child 1,
    .streamFailure stream 1
  ]

/-- A child failure followed by the next item failure is valid and started source input.
Witness: the child depends on the successful first item, and both failures have their
fixed non-null outcomes. The stream remains active after the child closes.
-/
theorem mixed_source_valid
    : ValidGraphEvents work mixedReceived
      ∧ inputsStarted work [mixedReceived] = true := by
  have first : ValidGraphEvents work [.streamItems stream [item]] :=
    source_valid.1.prefix ⟨[.streamFailure stream 1], rfl⟩
  have childFailed : ValidGraphEvents work
      [.streamItems stream [item], .taskFailure childTask 1] := by
    refine .append first ⟨_, _, _, child_known⟩ ?_ ?_
    · simp [GraphEvent.Fresh, GraphEvent.identities, item, childTask, firstItem]
    · exact ⟨_, _, _, child_known, by intro source same; cases same; simp [
        GraphEvent.successes, item]⟩
  refine ⟨.append childFailed ?_ ?_ ?_, by cbv⟩
  · exact ⟨_, _, _, _, stream_located, .empty, by simp⟩
  · simp [GraphEvent.Fresh, GraphEvent.identities, item]
  · exact ⟨_, _, _, _, stream_located,
      (by intro source impossible; cases impossible), .empty, rfl⟩

/-- Actual replay interleaves the child and stream failures, then terminates.
Witness: direct execution of the same queue and publisher; no output-admission premise.
-/
theorem mixed_output
    : ((State.initialize (Work.fromExecution work)).runNormalized [mixedReceived]).2
      = [mixedEvents ++ [.workQueueTermination]] := by cbv

/-- Batching, announcements, and root-item safety share one actual mixed replay witness.
Witness: the general canonical certificate theorem, retaining both failure kinds and
the exact publication matching rather than independently choosing a safe trace.
-/
theorem mixed_certificates
    : ∃ w : ConformancePlan.Witness,
        w.events = mixedEvents
        ∧ ConformancePlan.BatchShape work [mixedReceived] w
        ∧ ConformancePlan.AnnouncedFailures work w
        ∧ ConformancePlan.RootItemsSafe work mixedReceived w := by
  obtain ⟨w, history, batching, announced, _, safe⟩ :=
    ConformancePlan.rootItemCertificates (inputs := [mixedReceived]) generated
      mixed_source_valid.1 mixed_source_valid.2
  refine ⟨w, ?_, batching, announced, safe⟩
  rw [history]
  cbv

/-- The general mixed witness licenses the child and stream failures together.
Witness: instantiate mixed failure certificates for the actual interleaved source, keeping
both object and item failure accounting. No hand-built matching or item safety is supplied.
-/
theorem mixed_failure_certificates
    : ∃ w : ConformancePlan.Witness,
        w.events = mixedEvents
        ∧ ConformancePlan.BatchShape work [mixedReceived] w
        ∧ ConformancePlan.AnnouncedFailures work w
        ∧ ConformancePlan.SuccessfulItemsSafe work mixedReceived w
        ∧ ConformancePlan.UncancelledFailures work w := by
  obtain ⟨w, history, batching, announced, uncancelled, _, _, _, itemsSafe, _⟩ :=
    ConformancePlan.mixed_failureCertificates_with_cuts (inputs := [mixedReceived]) generated
      mixed_source_valid.1 mixed_source_valid.2
  refine ⟨w, ?_, batching, announced, itemsSafe, uncancelled⟩
  rw [history]
  cbv

/-- Dropping the item-publication premise would be unsound even for this generated work.
Witness: at an empty raw history the later item's failure cancels the first item through
their stream, then cancels C through its producer. This is not an admitted source trace.
-/
theorem unpublished_boundary_cancels_child
    : TaskCancelled work matching [] [(0, failedItem)] childTask := by
  refine ⟨0, by simp, Nat.le_refl _, ?_⟩
  have unpublished : ∀ occurrence, ¬Published matching [] occurrence := by
    rintro occurrence ⟨index, event, impossible, _⟩
    cases impossible
  apply Causality.TaskCancelled.producerCancelled ⟨_, _, child_known⟩ (unpublished _)
  apply Causality.TaskCancelled.owners ⟨_, _, first_known⟩ (unpublished _) (by simp)
  intro ref member
  obtain rfl := List.mem_singleton.mp member
  exact .task ⟨_, _, failed_known⟩ List.mem_cons_self (by simp [failedBefore])

end GraphQL.IncrementalDelivery.Tests.WorkSchedulerItemBoundary
