import Proofs.GraphQL.IncrementalDelivery.WorkQueueImplementation.FailureEventAdmission
import Tests.GraphQL.IncrementalDelivery.Execution

/-! The batching and announced-failure leaves share the same nonterminal history. -/

namespace GraphQL.IncrementalDelivery.Tests.WorkSchedulerFailureHistory
open GraphQL.IncrementalDelivery.Execution
open GraphQL.IncrementalDelivery.ReferenceWorkQueue
open GraphQL.IncrementalDelivery.ReferenceWorkQueue.ConformancePlan
open GraphQL.IncrementalDelivery.WorkQueueSemantics

private def left : DeliveryNode := ⟨0, [], some (.string "L")⟩
private def right : DeliveryNode := ⟨1, [], some (.string "R")⟩
private def leftTask : Occurrence := .executionGroup [1, 0]
private def rightTask : Occurrence := .executionGroup [1, 1, 0]

private def work : Execution.Work :=
  .combine .empty
    (.combine (.executionGroup [⟨left, []⟩] [] (.error 1) .empty)
      (.combine (.executionGroup [⟨right, []⟩] [] (.error 1) .empty) .empty))

private def first : GraphEvent := .taskFailure leftTask 1
private def second : GraphEvent := .taskFailure rightTask 1
private def initial : State := State.initialize (Work.fromExecution work)

/-- The two root failures are generated by independent deferred non-null fields.
Witness: aliases keep the selections distinct while the pure resolver fails both.
-/
theorem generated : ExecutedWork work := by
  refine ⟨Nat, schema, resolvers, [], 30, "Query", .object "Query" 0,
    [defer [field "required" [] [] (some "left")] (some "L"),
      defer [field "required" [] [] (some "right")] (some "R")], ?_⟩
  cbv

/-- Both failure inputs have fixed outcomes, fresh identities, and no producer dependency.
Witness: exact structural tasks; either host batching respects actual starts.
-/
theorem source_valid
    : ValidGraphEvents work [first, second]
      ∧ inputsStarted work [[first], [second]] = true
      ∧ inputsStarted work [[first, second]] = true := by
  have firstKnown : TaskAt work leftTask [left.key] none (.object [] (.error 1)) :=
    ⟨_, [], .error 1, .empty, [], rfl, rfl, rfl⟩
  have secondKnown : TaskAt work rightTask [right.key] none (.object [] (.error 1)) :=
    ⟨_, [], .error 1, .empty, [], rfl, rfl, rfl⟩
  have one : ValidGraphEvents work [first] :=
    .append .nil ⟨_, _, _, firstKnown⟩
      (by simp [first, GraphEvent.Fresh, GraphEvent.identities])
      ⟨_, _, _, firstKnown, by intro source impossible; cases impossible⟩
  exact ⟨
    .append one ⟨_, _, _, secondKnown⟩
      (by
        simp [first, second, leftTask, rightTask, GraphEvent.Fresh, GraphEvent.identities])
      ⟨_, _, _, secondKnown, by intro source impossible; cases impossible⟩,
    by cbv,
    by cbv
  ⟩

/-- Both errors remain in the nonterminal history at their original unbatched positions.
Witness: exact concrete output, including the one separate final marker.
-/
theorem actual_history
    : initial.nonterminalAtoms [[first], [second]]
        = [.groupFailure left 1, .groupFailure right 1]
      ∧ (initial.runNormalized [[first], [second]]).2
        = [[.groupFailure left 1], [.groupFailure right 1, .workQueueTermination]]
      ∧ initial.nonterminalAtoms [[first, second]]
        = initial.nonterminalAtoms [[first], [second]] := by
  cbv

/-- The terminal annotation adds no candidate and neither existing cut is moved.
Witness: the concrete selected-label construction retains cuts zero and one under both
batchings. The nonterminal-bound theorem therefore applies to a nonempty inventory.
-/
theorem actual_cuts
    : let publisher : IncrementalPublisher :=
        { active := initial.initialGroups ++ initial.initialStreams }
      sourceObjectFailureCuts 0
          (initial.eligibleFailureBlocks
            (initial.sourceRunBlocks publisher [[first], [second]]).2.2)
        = [(0, leftTask), (1, rightTask)]
      ∧ sourceObjectFailureCuts 0
          (initial.eligibleFailureBlocks
            (initial.sourceRunBlocks publisher [[first, second]]).2.2)
        = [(0, leftTask), (1, rightTask)] := by
  cbv

/-- The second actual failure is bounded by the retained prefix, not by the longer output.
Witness: the general source-cut theorem, with concrete membership supplied by `actual_cuts`.
-/
theorem last_cut_inside_nonterminal
    : 1 ≤ (initial.nonterminalAtoms [[first], [second]]).length := by
  apply initial.eligibleObjectFailureCuts_nonterminalBound [[first], [second]]
    (createWorkQueue_terminated _) (1, rightTask)
  rw [actual_cuts.1]
  simp

/-- Each batching has a joint certificate with identical history, matching, and cuts.
Witness: the two proved general leaves, not a separately chosen batching explanation.
Cancellation safety and full event admission are not asserted by this certificate.
-/
theorem joint_leaves (matching : PublicationMatching)
    : (∃ failures,
        let witness : Witness :=
          { events := initial.nonterminalAtoms [[first], [second]], matching, failures }
        BatchShape work [[first], [second]] witness ∧ AnnouncedFailures work witness)
      ∧ (∃ failures,
          let witness : Witness :=
            { events := initial.nonterminalAtoms [[first, second]], matching, failures }
          BatchShape work [[first, second]] witness ∧ AnnouncedFailures work witness) :=
  ⟨
    batchShape_and_announcedFailures (inputs := [[first], [second]])
      generated source_valid.1 source_valid.2.1 matching,
    batchShape_and_announcedFailures (inputs := [[first, second]])
      generated source_valid.1 source_valid.2.2 matching
  ⟩

/-- Both host batchings admit each error completion on their own shared failure witness.
Witness: the general failed-control construction retains both actual group errors and
derives their complete `EventAllowed` rules, including open IDs and exact positive totals.
-/
theorem failure_controls_admitted
    : ∀ inputs : List (List GraphEvent),
        inputs.flatten = [first, second]
        → inputsStarted work inputs = true
        → ∃ w : Witness,
            w.events = (initialQueue work).nonterminalAtoms inputs
            ∧ BatchShape work inputs w
            ∧ FailureWitness work (initialKeys work) w.matching w.events w.failures
            ∧ FailureAdmission work w := by
  intro inputs same started
  obtain ⟨w, history, shape, announced, uncancelled, admitted⟩ :=
    failureAdmission_certificates generated (same ▸ source_valid.1) started
  exact ⟨w, history, shape, failureWitness announced uncancelled, admitted⟩

end GraphQL.IncrementalDelivery.Tests.WorkSchedulerFailureHistory
