import Proofs.GraphQL.IncrementalDelivery.WorkQueueImplementation.RetirementIntegration
import Proofs.GraphQL.IncrementalDelivery.WorkQueueImplementation.UncancelledRetirementReplay
import Proofs.GraphQL.IncrementalDelivery.WorkQueueImplementation.OwnerReplayClosure
import Proofs.GraphQL.IncrementalDelivery.WorkQueueImplementation.RetiredHealthReplay
import Tests.GraphQL.IncrementalDelivery.Execution

/-! Actual stream integration prunes a taskless parent before announcing its child. -/

namespace GraphQL.IncrementalDelivery.Tests.WorkSchedulerRetirementIntegration
open GraphQL.IncrementalDelivery.Execution
open GraphQL.IncrementalDelivery.ReferenceWorkQueue
open GraphQL.IncrementalDelivery.WorkQueueSemantics

private def stream : DeliveryNode := { ref := 0, path := [.field "users"] }

private def parent (index : Nat) : DeliveryNode :=
  ⟨2 * index + 1, [.field "users", .index index], some (.string "P")⟩

private def child (index : Nat) : DeliveryNode :=
  ⟨2 * index + 2, [.field "users", .index index], some (.string "C")⟩

private def children (index : Nat) : Execution.Work :=
  .combine .empty
    (.combine
      (.executionGroup [⟨child index, [parent index]⟩] [.field "users", .index index]
        (.ok ([("name", .scalar ("name" ++ toString (index + 1)))], 0))
        (.combine .empty .empty))
      .empty)

private def selections : List Selection :=
  [field "users" [defer [defer [field "name"] (some "C")] (some "P")]
    [.stream (.boolean true) none (.int 0)]]

private def work : Execution.Work :=
  ((executeRootSelectionSetCore schema resolvers [] 30 "Query" (.object "Query" 0)
      selections).run
    0).1.work

private def initial : State := State.initialize (Work.fromExecution work)

private def item : StreamItem :=
  ⟨.item [0, 0, 1] 0, ⟨.object [], 0⟩, Work.fromExecution (children 0) [0, 0, 1, 0]⟩

private def integrated : State := initial.integrateStreamItem item

/-- The regression is generated by streamed objects with nested taskless defer P.
Witness: the defining pure query-execution equation, without substituting raw work.
-/
theorem generated : ExecutedWork work :=
  ⟨Nat, schema, resolvers, [], 30, "Query", .object "Query" 0, selections, rfl⟩

private theorem stream_located
    : Located work [0, 0, 1]
        (.stream stream
          [(.ok (.object [], 0), children 0), (.ok (.object [], 0), children 1)])
        none [] := by cbv

/-- The first streamed item has exactly the supplied value and lowered child work.
Witness: its structural stream position and the pure child-lowering equation.
-/
theorem matching : (GraphEvent.streamItems stream [item]).MatchesWork work := by
  intro received member
  obtain rfl := List.mem_singleton.mp member
  exact ⟨[stream.ref], none, .item stream_located rfl, by cbv⟩

/-- This input is a real accepted source prefix, not just a well-shaped child chunk.
Witness: stream readiness, the first item's fixed payload, and the actual start checker.
-/
theorem source_valid
    : ValidGraphEvents work [.streamItems stream [item]]
      ∧ inputsStarted work [[.streamItems stream [item]]] = true := by
  refine ⟨.append .nil matching ?_ ?_, by cbv⟩
  · simp [GraphEvent.Fresh, GraphEvent.identities, item]
  · refine ⟨_, _, _, _, stream_located, by simp, by simp, ?_, rfl⟩
    intro producer impossible
    cases impossible

/-- Initialization satisfies both retirement invariants, even before any groups appear.
Witness: the general generated-work initialization theorem.
-/
theorem initial_retirement
    : initial.RootAncestorsRetired work ∧ initial.HealthyRetiredAncestors work [] :=
  generated.initialRetirement

/-- Actual stream replay supplies the promoted child's missing-parent certificate.
Witness: the general structural replay theorem, including its real item handler and drain;
P is taskless and pruned, while C retains its nonempty generated ancestry.
-/
theorem stream_replay_missing_parent_retirement
    : (initial.runNormalized
        [[.streamItems stream [item]]]).1.MissingParentAncestorsRetired
        work :=
  generated.runNormalized_missingParentAncestorsRetired source_valid.1

/-- Accepted-inventory healthy retirement follows without a pending-owner premise.
Witness: structural replay closure plus the separately proved cancellation provenance.
-/
theorem stream_replay_healthy_retirement
    : (initial.runNormalized [[.streamItems stream [item]]]).1.HealthyRetiredAncestors
        work (initial.objectFailureContributions [.streamItems stream [item]]) :=
  generated.runNormalized_healthyRetiredAncestors _ source_valid.1 source_valid.2

/-- Streamed taskless-parent promotion also preserves healthy registered ownership.
Witness: the general started owner replay, with no child-availability callback.
-/
theorem stream_replay_owner_accounting
    : ∃ parents,
        (initial.runNormalized [[.streamItems stream [item]]]).1.OwnerAccounting
          work parents [.streamItems stream [item]] := by
  obtain ⟨parents, _, accounting⟩ := generated.runNormalized_ownerAccounting_of_started
    [[.streamItems stream [item]]] source_valid.1 source_valid.2
  exact ⟨parents, accounting⟩

/-- Actual stream integration supplies the missing-parent health boundary after pruning P.
Witness: general generated health replay, including the real item fold, activation, and
drain; no taskless-parent-specific historical health certificate is supplied.
-/
theorem stream_replay_retired_health
    : let queue := (initial.runNormalized [[.streamItems stream [item]]]).1
      queue.UncancelledRetiredHealthy work []
      ∧ queue.RootAncestorsHealthy work []
      ∧ queue.MissingParentAncestorsHealthy work [] :=
  generated.runNormalized_retiredHealth _ source_valid.1 source_valid.2

/-- Integrating the item preserves retirement through actual taskless-parent pruning.
Witness: matching source metadata, initial registry coverage, supported cancellations,
and the general joint integration theorem; no no-pruning premise is supplied.
-/
theorem stream_integration_retirement
    : integrated.RootAncestorsRetired work
      ∧ integrated.HealthyRetiredAncestors work [] := by
  obtain ⟨parents, canonical⟩ := generated.groupRecordsCanonical
  have links := createWorkQueue_childLinksCanonical (Work.fromExecution work) parents
    (fun _ member => workFromSpec_groups_parentCanonical Located.root canonical member)
  have cancellations := createWorkQueue_cancelledRecordsSupported (Work.fromExecution work) work []
  have supported := cancellations.maybeIntegrateWork item.work none (by
      intro group member
      obtain ⟨dependencies, known⟩ :=
        matching.streamItem_childGroups_recordAt List.mem_cons_self member
      refine ⟨dependencies, known, ?_⟩
      rw [canonical _ _ known]
      exact matching.streamItem_childGroups_parentCanonical canonical List.mem_cons_self member)
  exact initial.integrateStreamItem_retirement generated
    (createWorkQueue_groupNodesMatchWork work) links canonical
    (createWorkQueue_registration work).1 (createWorkQueue_registration work).2
    initial_retirement.1 initial_retirement.2 matching List.mem_cons_self supported

/-- Integration really retires P and promotes C, retaining C's nonempty parent link.
Witness: direct evaluation of the same executable integration step used by the theorem.
-/
theorem taskless_parent_pruned
    : integrated.RetiredGroup (parent 0).ref
      ∧ integrated.rootGroups = [(child 0).ref]
      ∧ (integrated.groupNode? (child 0).ref).map (fun node => node.group.parent)
        = some (some (parent 0).ref) := by
  refine ⟨⟨?_, ?_⟩, by cbv, by cbv⟩
  · have registry : integrated.registeredGroups = [(parent 0).ref, (child 0).ref] := by cbv
    rw [registry]
    exact List.mem_cons_self
  · have refs : integrated.groupNodes.map (fun node => node.group.node.ref)
        = [(child 0).ref] := by cbv
    rw [refs]
    decide

/-- The promoted child does not have empty defer dependencies.
Witness: generated canonical ancestry equates every C descriptor with its actual [P]
list. This rejects the former proof-helper claim that every stream release is parentless.
-/
theorem promoted_child_not_parentless
    : ¬∃ producer, NodeAt work (child 0) .group [] producer := by
  have known : NodeAt work (child 0) .group [(parent 0).ref] (some item.occurrence) :=
    ⟨[0, 0, 1, 0, 1, 0], _, _, _, _, _, ⟨child 0, [parent 0]⟩,
      by cbv, List.mem_cons_self, rfl, rfl⟩
  intro ⟨producer, alleged⟩
  obtain ⟨parents, canonical⟩ := generated.groupDependenciesCanonical
  have impossible := (canonical _ _ _ known).trans (canonical _ _ _ alleged).symm
  cases impossible

end GraphQL.IncrementalDelivery.Tests.WorkSchedulerRetirementIntegration
