import Proofs.GraphQL.IncrementalDelivery.WorkQueueImplementation.GroupPublicationAdmission
import Proofs.GraphQL.IncrementalDelivery.WorkQueueImplementation.AtomicBatching
import Proofs.GraphQL.IncrementalDelivery.WorkQueueSemantics.FiniteHistories
import Tests.GraphQL.IncrementalDelivery.Execution

/-! A buffered failed co-owner is a valid wire ID when a healthy contributor supports data. -/

namespace GraphQL.IncrementalDelivery.Tests.WorkSchedulerFailedOwnerRemapping
open GraphQL.IncrementalDelivery.Execution
open GraphQL.IncrementalDelivery.ReferenceWorkQueue
open GraphQL.IncrementalDelivery.WorkQueueSemantics

-----------------------------------------------------------------------------------------
-- Generated work, legal source settlements, and the actual remapped value
-----------------------------------------------------------------------------------------

private def successRoot : DeliveryNode := ⟨0, [], some (.string "S")⟩
private def failureRoot : DeliveryNode := ⟨1, [], some (.string "F")⟩
private def parent : DeliveryNode := ⟨2, [], some (.string "P")⟩
private def shallow : DeliveryNode := ⟨3, [], some (.string "D")⟩
private def deep : DeliveryNode := ⟨4, [.field "user"], some (.string "C")⟩

private def sharedTask : Occurrence := .executionGroup [0, 0, 1, 0]
private def failedTask : Occurrence := .executionGroup [0, 0, 1, 1, 0]
private def blockerTask : Occurrence := .executionGroup [1, 0]
private def parentTask : Occurrence := .executionGroup [1, 1, 0]

private def emptyChildren : Execution.Work := .combine .empty .empty

private def sharedValue : ExecutionGroupValue :=
  {
    deliveryGroups := [successRoot, shallow, deep],
    path := [.field "user"],
    data := [("name", .scalar "name1")]
  }

private def parentValue : ExecutionGroupValue :=
  { deliveryGroups := [parent], path := [], data := [("b", .scalar "b")] }

private def work : Execution.Work :=
  .combine
    (.combine
      (.combine .empty
        (.combine
          (.executionGroup [⟨successRoot, []⟩, ⟨shallow, [parent]⟩, ⟨deep, [parent]⟩]
            [.field "user"] (.ok (sharedValue.data, 0)) emptyChildren)
          (.combine
            (.executionGroup [⟨failureRoot, []⟩, ⟨deep, [parent]⟩]
              [.field "user"] (.error 1) .empty)
            .empty)))
      .empty)
    (.combine
      (.executionGroup [⟨successRoot, []⟩] [] (.ok ([("a", .scalar "a")], 0))
        emptyChildren)
      (.combine
        (.executionGroup [⟨parent, []⟩] [] (.ok (parentValue.data, 0)) emptyChildren)
        .empty))

private def failed : GraphEvent := .taskFailure failedTask 1
private def shared : GraphEvent := .taskSuccess sharedTask ⟨sharedValue, {}⟩
private def finish : GraphEvent := .taskSuccess parentTask ⟨parentValue, {}⟩
private def inputs : List (List GraphEvent) := [[failed, shared, finish]]

private def outputs : List WorkQueueEvent :=
  [
    .groupFailure failureRoot 1,
    .groupValues parent [parentValue],
    .groupSuccess parent [shallow, deep] [],
    .groupValues deep [sharedValue],
    .groupSuccess shallow [] [],
    .groupFailure deep 1
  ]

/-- The counterexample is generated by the existing finite pure query executor.
Witness: an initially selected user object, a shared success under S/D/C, a shared
non-null failure under F/C, and P's independent field. S's blocker retains the success
until P releases D before the already-failed, deeper C.
-/
theorem generated : ExecutedWork work := by
  refine ⟨Nat, schema, resolvers, [], 50, "Query", .object "Query" 0,
    [field "user" [field "name" [] [.skip (.boolean true)]],
      defer [field "user" [field "name"], field "a"] (some "S"),
      defer [field "user" [field "required"]] (some "F"),
      defer [field "b", defer [field "user" [field "name"]] (some "D"),
        field "user" [defer [field "name", field "required"] (some "C")]] (some "P")], ?_⟩
  cbv

private theorem shared_known
    : TaskAt work sharedTask
        [successRoot.key, shallow.key, deep.key] none
        (.object sharedValue.path (.ok (sharedValue.data, 0))) :=
  ⟨_, _, _, emptyChildren, [], by cbv, rfl, rfl⟩

private theorem failed_known
    : TaskAt work failedTask [failureRoot.key, deep.key] none
        (.object [.field "user"] (.error 1)) :=
  ⟨_, _, _, .empty, [], by cbv, rfl, rfl⟩

private theorem blocker_known
    : TaskAt work blockerTask [successRoot.key] none
        (.object [] (.ok ([("a", .scalar "a")], 0))) :=
  ⟨_, _, _, emptyChildren, [], by cbv, rfl, rfl⟩

private theorem parent_known
    : TaskAt work parentTask [parent.key] none (.object [] (.ok (parentValue.data, 0))) :=
  ⟨_, _, _, emptyChildren, [], by cbv, rfl, rfl⟩

/-- All three inputs have exact outcomes, fresh identities, and actual requested starts.
Witness: structural descriptors and direct evaluation of the unchanged start checker;
all tasks are root-generated, so no producer success is assumed without evidence.
-/
theorem source_valid_started
    : ValidGraphEvents work inputs.flatten ∧ inputsStarted work inputs = true := by
  have first : ValidGraphEvents work [failed] :=
    .append .nil ⟨_, _, _, failed_known⟩
      (by simp [failed, GraphEvent.Fresh, GraphEvent.identities])
      ⟨_, _, _, failed_known, by intro source impossible; cases impossible⟩
  have second : ValidGraphEvents work [failed, shared] :=
    .append first ⟨_, _, shared_known, by cbv, by cbv⟩
      (by simp [failed, shared, failedTask, sharedTask, GraphEvent.Fresh, GraphEvent.identities])
      ⟨_, _, _, shared_known, by intro source impossible; cases impossible⟩
  refine ⟨.append second ⟨_, _, parent_known, by cbv, by cbv⟩ ?_ ?_, by cbv⟩
  · simp [failed, shared, finish, failedTask, sharedTask, parentTask,
      GraphEvent.Fresh, GraphEvent.identities]
  · exact ⟨_, _, _, parent_known, by intro source impossible; cases impossible⟩

/-- The raw healthy D publication is reassigned to C before C's failure completion.
Witness: direct execution of the original queue and publisher. C was announced by P's
carrier, so its longer response path wins despite its earlier accepted failure.
-/
theorem actual_output
    : ((State.initialize (Work.fromExecution work)).runNormalized inputs).2
      = [outputs] := by cbv

/-- The raw queue uses healthy D; only the publisher changes the effective owner to C.
Witness: the source prefix retains C's error and D's settled success, and the final raw
handler emits the shared value under D. These are concrete executable-state checks.
-/
theorem raw_support_and_failed_candidate
    : (((State.initialize (Work.fromExecution work)).replayGraphEvents
          [failed, shared]).groupNode?
          deep.key).map
          GroupNode.failure
        = some (some 1)
      ∧ (((State.initialize (Work.fromExecution work)).replayGraphEvents
            [failed, shared]).groupNode?
          shallow.key).map
          (fun node => (node.pending, node.failure))
        = some (0, none)
      ∧ ((State.initialize (Work.fromExecution work)).handleGraphEvents
          inputs.flatten).2[3]?
        = some (.groupValues shallow [sharedValue]) := by
  constructor
  · cbv
  constructor <;> cbv

-----------------------------------------------------------------------------------------
-- The selected wire owner really has failed before the shared publication
-----------------------------------------------------------------------------------------

private theorem task_cases {occurrence owners producer payload}
    (known : TaskAt work occurrence owners producer payload)
    : occurrence = sharedTask
      ∨ occurrence = failedTask
      ∨ occurrence = blockerTask
      ∨ occurrence = parentTask := by
  have member := known.observationToken
  simpa [observationTokens, work, emptyChildren, sharedTask, failedTask, blockerTask,
    parentTask] using member

private theorem first_count {failures}
    (counts : NodeErrors work failures failureRoot.key 1)
    : failedTask ∈ failures := by
  apply Classical.byContradiction
  intro absent
  obtain ⟨contribution, known, total⟩ := counts
  have zero : ∀ occurrence ∈ failures, contribution occurrence = 0 := by
    intro occurrence member
    obtain ⟨owners, producer, payload, task, assigned⟩ := known occurrence member
    rcases task_cases task with rfl | rfl | rfl | rfl
    · obtain ⟨rfl, _, rfl⟩ := task.unique shared_known
      simpa [failureRoot, successRoot, shallow, deep] using assigned
    · exact False.elim (absent member)
    · obtain ⟨rfl, _, rfl⟩ := task.unique blocker_known
      simpa [failureRoot, successRoot] using assigned
    · obtain ⟨rfl, _, rfl⟩ := task.unique parent_known
      simpa [failureRoot, parent] using assigned
  have sumZero : (failures.map contribution).sum = 0 := by
    apply List.sum_eq_zero_iff_forall_eq_nat.mpr
    intro count member
    obtain ⟨occurrence, included, rfl⟩ := List.mem_map.mp member
    exact zero occurrence included
  omega

/-- The earlier reported shared failure reaches C before its remapped value.
Witness: F's one error forces the shared F/C failure at cut zero. This remains true under
the revised contract; the publication must use a different healthy supporter.
-/
theorem selected_owner_already_failed (matching : PublicationMatching)
    (failures : FailureCuts)
    (first
      : EventAllowed work (ConformancePlan.initialKeys work) matching [] failures
          (.groupFailure failureRoot 1))
    : NodeFailed work matching (outputs.take 3) failures deep.key := by
  have recorded : failedTask ∈ failedBefore failures 0 := by
    apply first_count
    simpa only [EventAllowed, List.length_nil, failedBefore_filter _ (Nat.le_refl _)]
      using first.2.2.2
  apply NodeFailed.task failed_known (by simp)
  exact failedBefore_subset failures (Nat.zero_le _) recorded

-----------------------------------------------------------------------------------------
-- The unchanged source and initial notices still satisfy all existing premises
-----------------------------------------------------------------------------------------

/-- The actual initial notices satisfy every unchanged initialization premise.
Witness: S, P, and F are root-generated groups with an unaccounted contributor each;
their metadata, fresh distinct keys, and empty dependency lists are explicit.
-/
theorem initialized
    : Initializes work (State.initialize (Work.fromExecution work)).initialGroups
        (State.initialize (Work.fromExecution work)).initialStreams := by
  have eligible {occurrence owners payload node}
      (known : TaskAt work occurrence owners none payload) (owner : node.key ∈ owners)
      : CanAnnounce work [] (fun _ => .executionGroup []) [] [] node .group [] none := by
    refine ⟨by simp [announcedKeys, pendingKeys],
      Or.inl ⟨by simp [NodeFailed], Or.inr ?_⟩, by simp, by simp⟩
    intro accounted
    rcases accounted occurrence owners ⟨_, _, known⟩ owner with cancelled | published
    · simp [TaskCancelled] at cancelled
    · simp [Published] at published
  change Initializes work [successRoot, parent, failureRoot] []
  refine ⟨⟨by decide, ?_, by simp⟩, by simp⟩
  intro node member
  simp only [List.mem_cons, List.not_mem_nil, or_false] at member
  rcases member with rfl | rfl | rfl
  · exact ⟨[], none,
      ⟨[1, 0], _, [], .ok ([("a", .scalar "a")], 0), emptyChildren, [],
        ⟨successRoot, []⟩, by cbv, List.mem_cons_self, rfl, rfl⟩,
      eligible blocker_known List.mem_cons_self⟩
  · exact ⟨[], none,
      ⟨[1, 1, 0], _, [], .ok (parentValue.data, 0), emptyChildren, [],
        ⟨parent, []⟩, by cbv, List.mem_cons_self, rfl, rfl⟩,
      eligible parent_known List.mem_cons_self⟩
  · exact ⟨[], none,
      ⟨[0, 0, 1, 1, 0], _, [.field "user"], .error 1, .empty, [],
        ⟨failureRoot, []⟩, by cbv, List.mem_cons_self, rfl, rfl⟩,
      eligible failed_known List.mem_cons_self⟩

-----------------------------------------------------------------------------------------
-- An explicit shared witness retains the failure and separates support from the wire ID
-----------------------------------------------------------------------------------------

private def initial : Keys := [0, 2, 1]

private def matching : PublicationMatching :=
  fun index =>
    if index = 3 then sharedTask else parentTask

private def failures : FailureCuts := [(0, failedTask)]

private theorem success_node : NodeAt work successRoot .group [] none :=
  ⟨
    [1, 0],
    _,
    [],
    .ok ([("a", .scalar "a")], 0),
    emptyChildren,
    [],
    ⟨successRoot, []⟩,
    by cbv,
    List.mem_cons_self,
    rfl,
    rfl
  ⟩

private theorem failure_node : NodeAt work failureRoot .group [] none :=
  ⟨
    [0, 0, 1, 1, 0],
    _,
    [.field "user"],
    .error 1,
    .empty,
    [],
    ⟨failureRoot, []⟩,
    by cbv,
    List.mem_cons_self,
    rfl,
    rfl
  ⟩

private theorem parent_node : NodeAt work parent .group [] none :=
  ⟨
    [1, 1, 0],
    _,
    [],
    .ok (parentValue.data, 0),
    emptyChildren,
    [],
    ⟨parent, []⟩,
    by cbv,
    List.mem_cons_self,
    rfl,
    rfl
  ⟩

private theorem shallow_node : NodeAt work shallow .group [parent.key] none :=
  ⟨
    [0, 0, 1, 0],
    _,
    sharedValue.path,
    .ok (sharedValue.data, 0),
    emptyChildren,
    [],
    ⟨shallow, [parent]⟩,
    by cbv,
    by simp [shallow, parent],
    rfl,
    rfl
  ⟩

private theorem deep_node : NodeAt work deep .group [parent.key] none :=
  ⟨
    [0, 0, 1, 0],
    _,
    sharedValue.path,
    .ok (sharedValue.data, 0),
    emptyChildren,
    [],
    ⟨deep, [parent]⟩,
    by cbv,
    by simp [deep, parent],
    rfl,
    rfl
  ⟩

/-- Every candidate descriptor is one of the five actual groups.
Witness: the structural key inventory and generated full-descriptor coherence.
-/
private theorem node_cases {node kind dependencies producer}
    (known : NodeAt work node kind dependencies producer)
    : node = successRoot
      ∨ node = shallow
      ∨ node = deep
      ∨ node = failureRoot
      ∨ node = parent := by
  have token := known.observationToken
  simp [observationTokens, work, emptyChildren, successRoot, shallow, deep,
    failureRoot, parent] at token
  rcases token with token | token | token | token | token | token | token
  all_goals first
    | exact Or.inl (generated.nodeKeyCoherent _ _ _ _ _ _ _ _ known success_node token)
    | exact Or.inr (Or.inl
        (generated.nodeKeyCoherent _ _ _ _ _ _ _ _ known shallow_node token))
    | exact Or.inr (Or.inr (Or.inl
        (generated.nodeKeyCoherent _ _ _ _ _ _ _ _ known deep_node token)))
    | exact Or.inr (Or.inr (Or.inr (Or.inl
        (generated.nodeKeyCoherent _ _ _ _ _ _ _ _ known failure_node token))))
    | exact Or.inr (Or.inr (Or.inr (Or.inr
        (generated.nodeKeyCoherent _ _ _ _ _ _ _ _ known parent_node token))))

/-- The single shared failure cannot invalidate a different root-supported group.
Witness: generated root causality reduces failure to that contributor or a failed ancestor.
-/
private theorem healthy_of_dependencies {node dependencies} (events : List WorkQueueEvent)
    (known : NodeAt work node .group dependencies none)
    (other : node.key ∉ [failureRoot.key, deep.key])
    (ancestors : ∀ key ∈ dependencies, ¬NodeFailed work matching events failures key)
    : ¬NodeFailed work matching events failures node.key := by
  intro failed
  rcases generated.groupFailure_withRootProducer known failed with direct | ancestor
  · obtain ⟨occurrence, owners, ⟨producer, payload, task⟩, owner, recorded⟩ := direct
    have same : occurrence = failedTask := by simpa [failedBefore, failures] using recorded
    subst occurrence
    exact other ((task.unique failed_known).1 ▸ owner)
  · obtain ⟨key, member, failed⟩ := ancestor
    exact ancestors key member failed

private theorem parent_healthy (events : List WorkQueueEvent)
    : ¬NodeFailed work matching events failures parent.key :=
  healthy_of_dependencies events parent_node (by decide) (by simp)

private theorem shallow_healthy (events : List WorkQueueEvent)
    : ¬NodeFailed work matching events failures shallow.key := by
  apply healthy_of_dependencies events shallow_node (by decide)
  intro key member
  obtain rfl := List.mem_singleton.mp member
  exact parent_healthy events

/-- A healthy contributor protects a root task from every historical cancellation cut.
Witness: owner cancellation contradicts that health; producer cases contradict rootness.
-/
private theorem root_uncancelled {occurrence owners payload key}
    (events : List WorkQueueEvent) (known : TaskAt work occurrence owners none payload)
    (member : key ∈ owners) (healthy : ¬NodeFailed work matching events failures key)
    : ¬TaskCancelled work matching events failures occurrence := by
  rintro ⟨cut, recorded, reached, cause⟩
  cases cause with
  | owners task _ _ failed =>
      obtain ⟨producer, result, task⟩ := task
      exact healthy ⟨cut, recorded, reached, failed key ((known.unique task).1 ▸ member)⟩
  | producerFailed task _ _ | producerCancelled task _ _ =>
      obtain ⟨owners, result, task⟩ := task
      cases (known.unique task).2.1

/-- The shared publication's matching index has not occurred in a prefix of length three.
Witness: every earlier matching entry names P's different task.
-/
private theorem shared_unpublished {events : List WorkQueueEvent}
    (length : events.length ≤ 3)
    : ¬Published matching events sharedTask := by
  rintro ⟨index, event, selected, _, same⟩
  have before := (List.getElem?_eq_some_iff.mp selected).1
  have different : index ≠ 3 := by omega
  simp [matching, different, parentTask, sharedTask] at same

/-- P's earlier value and the later shared value have their exact task identities.
Witness: the two explicit atomic indices in the unchanged executable output.
-/
private theorem parent_published : Published matching (outputs.take 2) parentTask :=
  ⟨1, .groupValues parent [parentValue], rfl, trivial, rfl⟩

private theorem shared_published : Published matching (outputs.take 4) sharedTask :=
  ⟨3, .groupValues deep [sharedValue], rfl, trivial, rfl⟩

/-- The one accepted failure is licensed by F at initialization.
Witness: its exact failed root task, announced F, and empty earlier failure inventory.
-/
private theorem failure_licensed
    : FailureWitness work initial matching outputs failures := by
  intro before cut occurrence after equal
  have sizes := congrArg List.length equal
  simp only [failures, List.length_append, List.length_cons, List.length_nil] at sizes
  have emptyBefore : before = [] := List.eq_nil_of_length_eq_zero (by omega)
  have emptyAfter : after = [] := List.eq_nil_of_length_eq_zero (by omega)
  subst before
  subst after
  have same : (0, failedTask) = (cut, occurrence) := by simpa [failures] using equal
  cases same
  refine ⟨by decide, by simp, ?_, by simp [TaskCancelled]⟩
  exact ⟨
    _,
    _,
    _,
    failed_known,
    rfl,
    .root ⟨_, _, failed_known⟩,
    failureRoot.key,
    by simp,
    by decide
  ⟩

/-- Both F and C report the same accepted error at their respective completion boundaries.
Witness: a singleton contribution inventory and exact task-owner membership.
-/
private theorem failed_errors (events : List WorkQueueEvent) (key : Nat)
    (owner : key ∈ [failureRoot.key, deep.key])
    : NodeErrors work (failedBefore failures events.length) key 1 := by
  refine ⟨fun _ => 1, ?_, by simp [failedBefore, failures]⟩
  intro occurrence member
  have same : occurrence = failedTask := by simpa [failedBefore, failures] using member
  subst occurrence
  exact ⟨_, _, _, failed_known, by simp [Payload.failure, owner]⟩

private theorem failure_allowed
    : EventAllowed work initial matching [] failures (.groupFailure failureRoot 1) := by
  refine ⟨
    ⟨[], none, failure_node⟩,
    by unfold Open; decide,
    ?_,
    failed_errors [] _ (by simp)
  ⟩
  exact NodeFailed.task failed_known (by simp) (by simp [failedBefore, failures])

/-- P's ordinary successful value uses its sole healthy contributor.
Witness: root readiness, fresh publication, and generated descriptor coherence.
-/
private theorem parent_value_allowed
    : EventAllowed work initial matching (outputs.take 1) failures
        (.groupValues parent [parentValue]) := by
  refine ⟨[parent.key], none, parentValue, rfl, parent_known, ?_, ?_⟩
  · refine ⟨
      ?_,
      root_uncancelled _ parent_known (by simp) (parent_healthy _),
      by simp,
      trivial
    ⟩
    rintro ⟨index, event, selected, value, _⟩
    cases index with
    | zero => cases selected; cases value
    | succ index => simp [outputs] at selected
  · have opened : OpenOwner work initial (outputs.take 1) [parent.key] parent :=
      ⟨⟨.group, [], none, parent_node⟩, by simp, by unfold Open; decide⟩
    refine ⟨opened, ⟨parent, opened, parent_healthy _⟩, ?_⟩
    intro other available
    obtain ⟨kind, dependencies, producer, known⟩ := available.1
    have same := generated.nodeKeyCoherent _ _ _ _ _ _ _ _ known parent_node
      (List.mem_singleton.mp available.2.1)
    simp [same]

/-- P's completion releases healthy D and failed C together, without a separate update.
Witness: P's task is published; D retains the shared success and C the recorded failure.
-/
private theorem parent_closure_allowed
    : EventAllowed work initial matching (outputs.take 2) failures
        (.groupSuccess parent [shallow, deep] []) := by
  refine ⟨⟨[], none, parent_node⟩, by unfold Open; decide, parent_healthy _, ?_, ?_⟩
  · intro occurrence owners ⟨producer, payload, task⟩ owner
    rcases task_cases task with rfl | rfl | rfl | rfl
    · rw [(task.unique shared_known).1] at owner
      simp [parent, successRoot, shallow, deep] at owner
    · rw [(task.unique failed_known).1] at owner
      simp [parent, failureRoot, deep] at owner
    · rw [(task.unique blocker_known).1] at owner
      simp [parent, successRoot] at owner
    · exact Or.inr parent_published
  · let before := outputs.take 2 ++ [WorkQueueEvent.groupSuccess parent [] []]
    have dependency : DependencySatisfied work initial matching before failures parent.key :=
      ⟨parent_healthy _, Or.inr (Or.inl (by decide))⟩
    refine ⟨by decide, ?_, by simp⟩
    intro node member
    simp only [List.mem_cons, List.not_mem_nil, or_false] at member
    rcases member with rfl | rfl
    · refine ⟨[parent.key], none, shallow_node, by decide,
        Or.inl ⟨shallow_healthy _, Or.inr ?_⟩, by simp, ?_⟩
      · intro accounted
        rcases accounted sharedTask _ ⟨_, _, shared_known⟩ (by simp) with cancelled | published
        · exact root_uncancelled before shared_known (by simp) (shallow_healthy _) cancelled
        · exact shared_unpublished (by decide : before.length ≤ 3) published
      · intro key member
        obtain rfl := List.mem_singleton.mp member
        exact dependency
    · refine ⟨[parent.key], none, deep_node, by decide,
        Or.inr ⟨rfl, ?_⟩, by simp, ?_⟩
      · exact ⟨failedTask, _, by simp [failedBefore, failures],
          ⟨_, _, failed_known⟩, by simp⟩
      · intro key member
        obtain rfl := List.mem_singleton.mp member
        exact dependency

/-- C's ID can carry the shared success while healthy D supplies publication support.
Witness: the shared root task is fresh and uncancelled; C is open and has maximal path.
-/
theorem shared_value_allowed
    : EventAllowed work initial matching (outputs.take 3) failures
        (.groupValues deep [sharedValue]) := by
  refine ⟨[successRoot.key, shallow.key, deep.key], none, sharedValue,
    rfl, shared_known, ?_, ?_⟩
  · exact ⟨shared_unpublished (by decide),
      root_uncancelled _ shared_known (by simp) (shallow_healthy _), by simp, trivial⟩
  · refine ⟨⟨⟨.group, [parent.key], none, deep_node⟩, by simp, by unfold Open; decide⟩,
      ⟨shallow, ⟨⟨.group, [parent.key], none, shallow_node⟩,
        by simp, by unfold Open; decide⟩, shallow_healthy _⟩, ?_⟩
    intro other available
    obtain ⟨kind, dependencies, producer, known⟩ := available.1
    rcases node_cases known with rfl | rfl | rfl | rfl | rfl <;> decide

/-- D closes only after its shared task has actually published under C's ID.
Witness: structural task enumeration identifies D's sole contributor with that publication.
-/
private theorem shallow_closure_allowed
    : EventAllowed work initial matching (outputs.take 4) failures
        (.groupSuccess shallow [] []) := by
  refine ⟨
    ⟨[parent.key], none, shallow_node⟩,
    by unfold Open; decide,
    shallow_healthy _,
    ?_,
    by simp [Announcements]
  ⟩
  intro occurrence owners ⟨producer, payload, task⟩ owner
  rcases task_cases task with rfl | rfl | rfl | rfl
  · exact Or.inr shared_published
  · rw [(task.unique failed_known).1] at owner
    simp [shallow, failureRoot, deep] at owner
  · rw [(task.unique blocker_known).1] at owner
    simp [shallow, successRoot] at owner
  · rw [(task.unique parent_known).1] at owner
    simp [shallow, parent] at owner

private theorem deep_failure_allowed
    : EventAllowed work initial matching (outputs.take 5) failures
        (.groupFailure deep 1) := by
  refine ⟨
    ⟨[parent.key], none, deep_node⟩,
    by unfold Open; decide,
    ?_,
    failed_errors _ _ (by simp)
  ⟩
  exact NodeFailed.task failed_known (by simp) (by simp [failedBefore, failures])

/-- Every atom of the original executable trace has one shared scheduler explanation.
Witness: the two actual publication indices and the retained F/C failure at cut zero.
-/
theorem atomic_explanation
    : Explains work (State.initialize (Work.fromExecution work)).initialGroups [] outputs
        matching failures := by
  refine ⟨initialized, failure_licensed, ?_⟩
  intro index event selected
  match index with
  | 0 => cases selected; exact failure_allowed
  | 1 => cases selected; exact parent_value_allowed
  | 2 => cases selected; exact parent_closure_allowed
  | 3 => cases selected; exact shared_value_allowed
  | 4 => cases selected; exact shallow_closure_allowed
  | 5 => cases selected; exact deep_failure_allowed
  | index + 6 => simp [outputs] at selected

/-- The unchanged batched executable output is admitted as an interrupted prefix.
Witness: use its exact atomic explanation and retain every event in the actual batch.
The unrelated S task is still pending, so no terminal-run claim is made.
-/
theorem actual_prefix_admissible
    : AdmissiblePrefix work
        ((State.initialize (Work.fromExecution work)).normalizedHistory inputs) := by
  refine ⟨outputs, matching, failures, atomic_explanation, ?_⟩
  rw [show ((State.initialize (Work.fromExecution work)).normalizedHistory inputs).batches
    = [outputs] from actual_output]
  exact .cons (by decide)
    (.separate _
      (.separate _ (.separate _ (.separate _ (.separate _ (.separate _ .nil))))))
    .nil

/-- The revised contract accepts the exact history previously refuted, without filtering.
Witness: the explicit admitted prefix, with unchanged generated work and source events.
-/
theorem actual_history_valid
    : ValidHistory work
        ((State.initialize (Work.fromExecution work)).normalizedHistory inputs) :=
  Or.inl actual_prefix_admissible

/-- The admitted publication really selects a failed owner, not a delayed failure cut.
Witness: the first completion forces C's failure while D supplies the successful value's
healthy support in the same explicit explanation.
-/
theorem failed_owner_publication
    : NodeFailed work matching (outputs.take 3) failures deep.key
      ∧ EventAllowed work initial matching (outputs.take 3) failures
          (.groupValues deep [sharedValue]) :=
  ⟨selected_owner_already_failed matching failures failure_allowed, shared_value_allowed⟩

/-- The general shared witness recovers an available contributor of its exact matched
task even though the wire ID is already failed. Witness: apply the generic raw-pair,
contributor, and indexed ledger bridges, not the hand-written explanation, to the
unchanged generated execution and source history.
-/
theorem generic_healthy_release
    : ∃ w : ConformancePlan.Witness,
        w.events = outputs
        ∧ NodeFailed work w.matching (w.events.take 3) w.failures deep.key
        ∧ ∃ origin
              : GroupPublicationOrigin
                  {
                    active :=
                      (State.initialize (Work.fromExecution work)).initialGroups
                      ++ (State.initialize (Work.fromExecution work)).initialStreams
                  }
                  ((State.initialize (Work.fromExecution work)).rawEventReplay
                    inputs.flatten).2
                  3 deep [sharedValue],
            origin.group.key ≠ deep.key
            ∧ (∃ producer,
                TaskAt work (w.matching 3)
                  (origin.value.deliveryGroups.map DeliveryNode.key) producer
                  (.object origin.value.path
                    (.ok (origin.value.data, origin.value.errors))))
            ∧ HealthyOpenOwner work initial w.matching (w.events.take 3) w.failures
                (origin.value.deliveryGroups.map DeliveryNode.key) origin.group := by
  obtain ⟨valid, started⟩ := source_valid_started
  obtain ⟨w, history, _, _, _, failuresAllowed, _, _, _, _, ledger, releases⟩ :=
    ConformancePlan.mixed_groupReleaseCertificates generated valid started
  have same : w.events = outputs := by
    rw [history]
    unfold State.nonterminalAtoms ConformancePlan.initialQueue
    rw [actual_output]
    simp [outputs, publicationAtoms]
  have firstAllowed := failuresAllowed.1 0 failureRoot 1 (by rw [same]; rfl)
  have failed : NodeFailed work w.matching (w.events.take 3) w.failures deep.key := by
    rw [same]
    exact selected_owner_already_failed w.matching w.failures (by
      simpa only [same, ConformancePlan.initialKeys, ConformancePlan.initialQueue,
        List.take_zero] using firstAllowed)
  obtain ⟨origin, known, available⟩ :=
    releases.matched_available valid started history ledger
    (show w.events[3]? = some (.groupValues deep [sharedValue]) from
      by rw [same]; rfl)
  refine ⟨w, same, failed, origin, ?_, known, available⟩
  intro equal
  exact available.2 (equal ▸ failed)

/-- The generic shared witness proves the full owner rule even for this failed wire ID.
Witness: actual group-notice freshness, publisher registry agreement, and exact matched
contributors; no custom publication matching or assumed registry invariant is supplied.
-/
theorem generic_failed_owner_rule
    : ∃ w : ConformancePlan.Witness,
        w.events = outputs
        ∧ NodeFailed work w.matching (w.events.take 3) w.failures deep.key
        ∧ ∃ owners producer path data errors,
            TaskAt work (w.matching 3) owners producer (.object path (.ok (data, errors)))
            ∧ PublicationOwner work initial w.matching (w.events.take 3) w.failures owners
                deep := by
  obtain ⟨valid, started⟩ := source_valid_started
  obtain ⟨w, history, _, _, _, failuresAllowed, _, _, _, _, ledger, releases⟩ :=
    ConformancePlan.mixed_groupReleaseCertificates generated valid started
  have same : w.events = outputs := by
    rw [history]
    unfold State.nonterminalAtoms ConformancePlan.initialQueue
    rw [actual_output]
    simp [outputs, publicationAtoms]
  have firstAllowed := failuresAllowed.1 0 failureRoot 1 (by rw [same]; rfl)
  have failed : NodeFailed work w.matching (w.events.take 3) w.failures deep.key := by
    rw [same]
    exact selected_owner_already_failed w.matching w.failures (by
      simpa only [same, ConformancePlan.initialKeys, ConformancePlan.initialQueue,
        List.take_zero] using firstAllowed)
  obtain ⟨owners, producer, value, known, _, owner⟩ :=
    releases.matched_owner generated valid started history ledger
      (show w.events[3]? = some (.groupValues deep [sharedValue]) from
        by rw [same]; rfl)
  exact ⟨
    w,
    same,
    failed,
    owners,
    producer,
    value.path,
    value.data,
    value.errors,
    known,
    owner
  ⟩

/-- General construction admits the remapped value even though its wire owner has failed.
Witness: the full object-admission theorem shares the canonical mixed matching and cuts;
the first actual failure still proves C failed before the value. No custom explanation or
fixture-specific cancellation argument is supplied to the publication proof.
-/
theorem generic_failed_owner_admission
    : ∃ w : ConformancePlan.Witness,
        w.events = outputs
        ∧ NodeFailed work w.matching (w.events.take 3) w.failures deep.key
        ∧ EventAllowed work (ConformancePlan.initialKeys work) w.matching
            (w.events.take 3) w.failures
            (.groupValues deep [sharedValue]) := by
  obtain ⟨valid, started⟩ := source_valid_started
  obtain ⟨w, history, _, _, _, failuresAllowed, _, _, _, _, _, _, _, _, publications⟩ :=
    ConformancePlan.mixed_groupPublicationCertificates generated valid started
  have same : w.events = outputs := by
    rw [history]
    unfold State.nonterminalAtoms ConformancePlan.initialQueue
    rw [actual_output]
    simp [outputs, publicationAtoms]
  have firstAllowed := failuresAllowed.1 0 failureRoot 1 (by rw [same]; rfl)
  have failed : NodeFailed work w.matching (w.events.take 3) w.failures deep.key := by
    rw [same]
    exact selected_owner_already_failed w.matching w.failures (by
      simpa only [same, ConformancePlan.initialKeys, ConformancePlan.initialQueue,
        List.take_zero] using firstAllowed)
  exact ⟨w, same, failed, publications 3 deep [sharedValue] (by rw [same]; rfl)⟩

end GraphQL.IncrementalDelivery.Tests.WorkSchedulerFailedOwnerRemapping
