import Proofs.GraphQL.IncrementalDelivery.WorkQueueImplementation.CanonicalItemStreamFreshness
import Proofs.GraphQL.IncrementalDelivery.WorkQueueImplementation.GroupStreamNoticeUniqueness

/-! Stream registration rejects reused closed keys and repeated item-batch descriptors. -/

namespace GraphQL.IncrementalDelivery.Tests.WorkSchedulerStreamNotices
open GraphQL.IncrementalDelivery.ReferenceWorkQueue
open GraphQL.IncrementalDelivery.WorkQueueSemantics

private def outer : Execution.DeliveryNode := { key := 0, path := [] }
private def closed : Execution.DeliveryNode := { key := 1, path := [] }
private def child : Execution.DeliveryNode := { key := 2, path := [] }
private def initial : State := State.initialize { streams := [⟨outer⟩, ⟨closed⟩] }
private def afterClose : State := (initial.streamSuccess closed).1

private def items : List StreamItem :=
  [
    ⟨.item [] 0, ⟨.null, 0⟩, { streams := [⟨closed⟩, ⟨child⟩, ⟨child⟩] }⟩,
    ⟨.item [] 1, ⟨.null, 0⟩, { streams := [⟨child⟩, ⟨closed⟩] }⟩
  ]

/-- Reusing a closed key and repeating a new descriptor still yields one new notice.
Witness: direct execution of the registration fold across both raw items. The raw payload
is deliberately permissive; this does not claim it is generated by a valid query.
-/
theorem repeated_descriptors_single_notice
    : (afterClose.streamItems outer items).2.flatMap rawStreamNoticeKeys
      = [child.key] := by
  cbv

/-- The closed stream remains registered and is not reactivated by either item.
Witness: its old key survives registry bookkeeping but is absent from the active-root list
after the actual handler; only the fresh child is activated alongside the outer stream.
-/
theorem closed_stream_not_reactivated
    : (afterClose.streamItems outer items).1.rootStreams = [outer.key, child.key] := by
  cbv

/-- The generic raw theorem excludes every old registration for the concrete item carrier.
Witness: the handler's exact first output and its multi-item fresh-selection invariant.
-/
theorem item_carrier_fresh
    : child.key ∉ afterClose.streams.map (fun stream => stream.node.key) := by
  have selected
      : (afterClose.streamItems outer items).2[0]?
        = some (.streamValues outer [⟨.null, 0⟩, ⟨.null, 0⟩] [] [child]) := by
    cbv
  exact (afterClose.streamItems_notices_fresh outer items selected).2 child
    List.mem_cons_self

/-- Valid initialized replay supplies unique group-carried stream keys without admission.
Witness: the generic inventory and generated structural producer separation theorem.
-/
theorem group_carrier_unique {work : Execution.Work} {batches : List (List GraphEvent)}
    (generated : ExecutedWork work) (valid : ValidGraphEvents work batches.flatten)
    (group : GroupNode)
    : ((((State.initialize (Work.fromExecution work)).runNormalized
          batches).1.finishGroupSuccess
          group).2.2.newStreams.map
        Execution.DeliveryNode.key).Nodup :=
  createWorkQueue_runNormalized_groupStreamKeys_nodup generated valid group

private def taskQueue : State :=
  State.initialize
    {
      groups := [⟨outer, none⟩, ⟨closed, none⟩]
      tasks := [⟨.executionGroup [], [outer, closed]⟩]
    }

private def taskResult : TaskResult :=
  {
    value := { path := [], data := [], errors := 0, deliveryGroups := [outer, closed] },
    work := { streams := [⟨child⟩, ⟨child⟩] }
  }

/-- Shared owners and duplicate raw descriptors still release the child stream only once.
Witness: actual task-success execution; the first owner removes the shared task and the
second owner cannot release its child links again. The raw payload need not be generated.
-/
theorem shared_task_single_stream_notice
    : (taskQueue.taskSuccess (.executionGroup []) taskResult).2.flatMap
        rawStreamNoticeKeys
      = [child.key] := by
  cbv

/-- Stream-link inventory remains true after shared-task release and a duplicate settlement.
Witness: the arbitrary-input replay theorem, not a source-validity assumption.
-/
theorem duplicate_settlement_inventory
    : ((taskQueue.runNormalized
          [
            [.taskSuccess (.executionGroup []) taskResult],
            [.taskSuccess (.executionGroup []) taskResult]
          ]).1).ChildStreamInventory :=
  createWorkQueue_runNormalized_childStreamInventory _ _

end GraphQL.IncrementalDelivery.Tests.WorkSchedulerStreamNotices
