import Proofs.GraphQL.IncrementalDelivery.WorkQueueImplementation
import Proofs.GraphQL.IncrementalDelivery.WorkQueueSemantics.FiniteHistories
import Proofs.GraphQL.IncrementalDelivery.Correctness.Initialization
import Tests.GraphQL.IncrementalDelivery.Execution

/-! A shared failure can outlive its only announced owner. -/

namespace GraphQL.IncrementalDelivery.Tests.WorkSchedulerSilentFailures
open GraphQL.IncrementalDelivery.Execution
open GraphQL.IncrementalDelivery.ReferenceWorkQueue
open GraphQL.IncrementalDelivery.WorkQueueSemantics

-----------------------------------------------------------------------------------------
-- Generated shared work and the actual accepted settlement sequence
-----------------------------------------------------------------------------------------

private def node (key : Nat) (label : String) : DeliveryNode :=
  { key, path := [], label := some (.string label) }

private def root : DeliveryNode := node 0 "R"
private def parent : DeliveryNode := node 1 "P"
private def child : DeliveryNode := node 2 "C"
private def firstTask : Occurrence := .executionGroup [1, 0]
private def sharedTask : Occurrence := .executionGroup [1, 1, 0]
private def parentTask : Occurrence := .executionGroup [1, 1, 1, 0]
private def parentData : List (Name × ResponseValue) := [("a", .scalar "a")]

private def work : Execution.Work :=
  .combine .empty
    (.combine (.executionGroup [⟨root, []⟩] [] (.error 1) .empty)
      (.combine (.executionGroup [⟨root, []⟩, ⟨child, [parent]⟩] [] (.error 2) .empty)
        (.combine
          (.executionGroup [⟨parent, []⟩] [] (.ok (parentData, 0))
            (.combine .empty .empty))
          .empty)))

private def selections : List Selection :=
  [
    defer [field "required" [] [] (some "first"), field "fail", field "required"]
      (some "R"),
    defer [field "a", defer [field "fail", field "required"] (some "C")] (some "P")
  ]

private def first : GraphEvent := .taskFailure firstTask 1
private def shared : GraphEvent := .taskFailure sharedTask 2

private def finish : GraphEvent :=
  .taskSuccess parentTask
    {
      value := { deliveryGroups := [parent], path := [], data := parentData },
      work := Work.fromExecution (.combine .empty .empty) [1, 1, 1, 0, 0]
    }

private def inputs : List (List GraphEvent) := [[first], [shared], [finish]]
private def queue : State := State.initialize (Work.fromExecution work)

/-- The example is generated by actual finite query execution, with two distinct failures.
Witness: evaluate the displayed selection set against the shared pure resolver fixture.
-/
theorem generated : ExecutedWork work := by
  refine ⟨Nat, schema, resolvers, [], 30, "Query", .object "Query" 0, selections, ?_⟩
  cbv

/-- The first failure belongs only to R and reports one non-null field error.
Witness: the fixed generated partition at its structural address.
-/
private theorem first_known
    : TaskAt work firstTask [root.key] none (.object [] (.error 1)) :=
  TaskAt.executionGroup (groups := [⟨root, []⟩]) (children := .empty) (owners := [])
    (by cbv)

/-- The second failure is shared between R and the still-unannounced child C.
Witness: the generated shared partition; C depends on P, not on R.
-/
private theorem shared_known
    : TaskAt work sharedTask [root.key, child.key] none (.object [] (.error 2)) :=
  TaskAt.executionGroup (groups := [⟨root, []⟩, ⟨child, [parent]⟩])
    (children := .empty) (owners := []) (by cbv)

/-- P has an independent successful task with no structural producer.
Witness: its exact generated partition and fixed scalar data.
-/
private theorem parent_known
    : TaskAt work parentTask [parent.key] none (.object [] (.ok (parentData, 0))) :=
  TaskAt.executionGroup (groups := [⟨parent, []⟩])
    (children := .combine .empty .empty) (owners := []) (by cbv)

/-- Both failures and the parent success obey fixed outcomes, freshness, and producer order.
Witness: three source append rules over the generated root tasks.
-/
theorem inputs_valid : ValidGraphEvents work inputs.flatten := by
  have one : ValidGraphEvents work [first] :=
    .append .nil ⟨_, _, _, first_known⟩
      (by simp [first, GraphEvent.Fresh, GraphEvent.identities])
      ⟨_, _, _, first_known, by intro source impossible; cases impossible⟩
  have two : ValidGraphEvents work [first, shared] :=
    .append one ⟨_, _, _, shared_known⟩
      (by simp [first, shared, firstTask, sharedTask, GraphEvent.Fresh,
        GraphEvent.identities])
      ⟨_, _, _, shared_known, by intro source impossible; cases impossible⟩
  exact .append two ⟨_, _, parent_known, by cbv, by cbv⟩
    (by simp [first, shared, finish, firstTask, sharedTask, parentTask, GraphEvent.Fresh,
      GraphEvent.identities])
    ⟨_, _, _, parent_known, by intro source impossible; cases impossible⟩

/-- The shared failure is accepted after R closes, since C still retains the started task.
Witness: evaluate the original queue start/stop checker, not an alternative source policy.
-/
theorem inputs_started : inputsStarted work inputs = true := by cbv

/-- The second shared failure is retained until the child receives its pending notice.
Witness: actual replay reports the child's two errors after P releases it, then terminates.
-/
theorem output
    : (queue.runNormalized inputs).2
        = [
          [.groupFailure root 1],
          [
            .groupValues parent
              [{ path := [], data := parentData, deliveryGroups := [parent] }],
            .groupSuccess parent [child] [],
            .groupFailure child 2,
            .workQueueTermination
          ]
        ]
      ∧ (queue.runNormalized inputs).1.terminated = true := by
  constructor <;> cbv

/-- The queue announces exactly R and P, both root-produced groups with no dependencies.
Witness: exact initialization and the original empty-history announcement rules.
-/
theorem initialized : Initializes work queue.initialGroups queue.initialStreams := by
  have rootKnown : NodeAt work root .group [] none :=
    NodeAt.group (work := work) (groups := [⟨root, []⟩]) (address := [1, 0])
      (path := []) (producer := none) (group := ⟨root, []⟩)
      (result := .error 1) (children := .empty) (owners := [])
      (by cbv) (by simp)
  have parentKnown : NodeAt work parent .group [] none :=
    NodeAt.group (work := work) (groups := [⟨parent, []⟩]) (address := [1, 1, 1, 0])
      (path := []) (producer := none) (group := ⟨parent, []⟩)
      (result := .ok (parentData, 0)) (children := .combine .empty .empty) (owners := [])
      (by cbv) (by simp)
  have eligible (group : DeliveryNode) (known : NodeAt work group .group [] none)
      : CanAnnounce work [] (fun _ => .executionGroup []) [] [] group .group [] none :=
    ⟨by simp [announcedKeys, pendingKeys], Or.inl ⟨fun failure => failure.nonempty rfl,
        Or.inr (group_not_initially_accounted known)⟩, by simp, by simp⟩
  have notices : queue.initialGroups = [root, parent] ∧ queue.initialStreams = [] := by cbv
  rw [notices.1, notices.2]
  refine ⟨⟨by decide, ?_, by simp⟩, by simp⟩
  intro group member
  rcases List.mem_cons.mp member with rfl | member
  · exact ⟨[], none, rootKnown, eligible _ rootKnown⟩
  · have same := List.mem_singleton.mp member
    subst group
    exact ⟨[], none, parentKnown, eligible _ parentKnown⟩

private def source : EventSource (List GraphEvent) :=
  { admissible := fun batches => batches.IsPrefix inputs, finished := fun _ => False }

/-- A prefix-closed opaque source admits this finite input trace and obeys every source law.
Witness: prefix closure of the checked fixed-outcome, fresh, producer-ordered settlements.
-/
theorem source_validGraphEvents
    : ∀ batches, source.admissible batches → ValidGraphEvents work batches.flatten := by
  intro batches admitted
  obtain ⟨tail, same⟩ := admitted
  apply inputs_valid.prefix
  exact ⟨tail.flatten, by rw [← List.flatten_append, ← same]⟩

/-- Every source prefix settles only actually started tasks before queue termination.
Witness: enumerate the four permitted batch prefixes and evaluate the public checker.
-/
theorem source_respectsStarts
    : ∀ batches, source.admissible batches → inputsStarted work batches = true := by
  intro batches admitted
  change batches.IsPrefix inputs at admitted
  have same := List.prefix_iff_eq_take.mp admitted
  have bound : batches.length ≤ 3 := admitted.length_le
  have lengths : batches.length = 0 ∨ batches.length = 1 ∨ batches.length = 2
      ∨ batches.length = 3 := by omega
  rcases lengths with length | length | length | length <;> rw [same, length] <;> cbv

/-- This source satisfies both graph-event validity and actual-start admission.
Witness: the checked prefixes of its fixed finite input trace.
-/
theorem source_conforms : source.ValidFor work :=
  ⟨
    rfl,
    ⟨inputs, rfl⟩,
    fun _ _ before after => before.trans after,
    fun batches admitted =>
      ⟨source_validGraphEvents batches admitted, source_respectsStarts batches admitted⟩
  ⟩

/-- The former counterexample now satisfies the public conformance statement.
Witness: the completed implementation theorem, without any internal queue premise.
-/
theorem conformance : ReferenceWorkQueue.createWorkQueueForScheduleConforms :=
  createWorkQueueForScheduleConforms_holds

/-- The actual output, including the retained silent failure, is an admitted complete run.
Witness: instantiate conformance with the checked generated work and prefix-closed source.
-/
theorem output_admitted
    : AdmissibleRun work
        ⟨queue.initialGroups, queue.initialStreams, (queue.runNormalized inputs).2⟩ := by
  have conforms := conformance work source generated (by decide) source_conforms
  have finished : (createWorkQueueForSchedule work source).workEventStream.finished
      (queue.runNormalized inputs).2 :=
    ⟨inputs, List.prefix_refl _, rfl, output.2⟩
  exact ((conforms.2.2.2 _).mp finished).2

end GraphQL.IncrementalDelivery.Tests.WorkSchedulerSilentFailures
