import Proofs.GraphQL.IncrementalDelivery.WorkQueueImplementation.ConformanceBatchShape
import Tests.GraphQL.IncrementalDelivery.Execution

/-! Terminal suffixes retain silent settlements, shared values, and completions. -/

namespace GraphQL.IncrementalDelivery.Tests.WorkSchedulerTermination
open GraphQL.IncrementalDelivery.Execution
open GraphQL.IncrementalDelivery.ReferenceWorkQueue
open GraphQL.IncrementalDelivery.ReferenceWorkQueue.ConformancePlan
open GraphQL.IncrementalDelivery.WorkQueueSemantics

private def parent : DeliveryNode := ⟨0, [], some (.string "P")⟩
private def other : DeliveryNode := ⟨1, [], some (.string "Q")⟩
private def firstTask : Occurrence := .executionGroup [1, 0]
private def sharedTask : Occurrence := .executionGroup [1, 1, 0]

private def firstValue : ExecutionGroupValue :=
  { path := [], data := [("fail", .null)], errors := 1, deliveryGroups := [parent] }

private def sharedValue : ExecutionGroupValue :=
  {
    path := [],
    data := [("b", .scalar "b")],
    errors := 0,
    deliveryGroups := [parent, other]
  }

private def noChildren : Execution.Work := .combine .empty .empty

private def work : Execution.Work :=
  .combine .empty
    (.combine (.executionGroup [⟨parent, []⟩] [] (.ok (firstValue.data, 1)) noChildren)
      (.combine
        (.executionGroup [⟨parent, []⟩, ⟨other, []⟩] [] (.ok (sharedValue.data, 0))
          noChildren) .empty))

private def first : GraphEvent := .taskSuccess firstTask { value := firstValue }
private def shared : GraphEvent := .taskSuccess sharedTask { value := sharedValue }
private def initial : State := State.initialize (Work.fromExecution work)

/-- The fixture is generated by overlapping defers with a nullable resolver failure.
Witness: pure execution yields one private task and one task shared by P and Q.
-/
theorem generated : ExecutedWork work := by
  refine ⟨Nat, schema, resolvers, [], 50, "Query", .object "Query" 0,
    [defer [field "fail", field "b"] (some "P"), defer [field "b"] (some "Q")], ?_⟩
  cbv

/-- Both events match generated work, are fresh, and obey producer/start discipline.
Witness: the two structural task descriptors and the concrete split-batch start check.
-/
theorem source_valid
    : ValidGraphEvents work [first, shared]
      ∧ inputsStarted work [[first], [shared]] = true := by
  have firstKnown : TaskAt work firstTask [parent.key] none
      (.object [] (.ok (firstValue.data, 1))) :=
    ⟨_, [], _, noChildren, [], rfl, rfl, rfl⟩
  have sharedKnown : TaskAt work sharedTask [parent.key, other.key] none
      (.object [] (.ok (sharedValue.data, 0))) :=
    ⟨_, [], _, noChildren, [], rfl, rfl, rfl⟩
  have one : ValidGraphEvents work [first] :=
    .append .nil ⟨_, _, firstKnown, rfl, rfl⟩
      (by simp [first, GraphEvent.Fresh, GraphEvent.identities])
      ⟨_, _, _, firstKnown, by intro source impossible; cases impossible⟩
  exact ⟨
    .append one ⟨_, _, sharedKnown, rfl, rfl⟩
      (by
        simp [first, shared, firstTask, sharedTask, GraphEvent.Fresh, GraphEvent.identities])
      ⟨_, _, _, sharedKnown, by intro source impossible; cases impossible⟩,
    by cbv
  ⟩

/-- A silent successful settlement neither emits a marker nor terminates the queue.
Witness: the stored value still waits for the shared task; the general shape theorem
does not mistake an empty output list for a finished history.
-/
theorem silent_prefix
    : initial.nonterminalAtoms [[first]] = []
      ∧ (initial.runNormalized [[first]]).1.terminated = false
      ∧ WorkQueueEvent.workQueueTermination
        ∉ (initial.runNormalized [[first]]).2.flatten := by
  have running : (initial.runNormalized [[first]]).1.terminated = false := by cbv
  exact ⟨
    by cbv,
    running,
    by
      rw [initial.runNormalized_termination_mem [[first]] (createWorkQueue_terminated _)]
      simp [running]
  ⟩

/-- Split and joined host batches retain both values, their errors, and both closures.
Witness: concrete output evaluation; only the final terminal atom is projected away.
-/
theorem exact_nonterminal_history
    : initial.nonterminalAtoms [[first], [shared]]
        = [
          .groupValues parent
            [{
              path := [],
              data := firstValue.data,
              errors := 1,
              deliveryGroups := firstValue.deliveryGroups
            }],
          .groupValues parent
            [{
              path := [],
              data := sharedValue.data,
              errors := 0,
              deliveryGroups := sharedValue.deliveryGroups
            }],
          .groupSuccess parent [] [],
          .groupSuccess other [] []
        ]
      ∧ initial.nonterminalAtoms [[first, shared]]
        = initial.nonterminalAtoms [[first], [shared]]
      ∧ (initial.runNormalized [[first], [shared]]).1.terminated = true := by
  cbv

/-- The general batching leaf certifies these exact histories without assumptions about
the eventual matching or cuts. Witness: valid input shape, for both host batchings.
-/
theorem batching (matching : PublicationMatching) (failures : FailureCuts)
    : BatchShape work [[first], [shared]]
        { events := initial.nonterminalAtoms [[first], [shared]], matching, failures }
      ∧ BatchShape work [[first, shared]]
          { events := initial.nonterminalAtoms [[first, shared]], matching, failures } :=
  ⟨
    batchShape_holds source_valid.1 matching failures,
    batchShape_holds source_valid.1 matching failures
  ⟩

/-- Later supplied batches cannot duplicate the final marker or change prior atoms.
Witness: the general absorbing-state theorem, including arbitrarily invalid late inputs.
Such late inputs need not be admitted by the host-source contract.
-/
theorem after_termination (later : List (List GraphEvent))
    : initial.nonterminalAtoms ([[first], [shared]] ++ later)
        = initial.nonterminalAtoms [[first], [shared]]
      ∧ (initial.runNormalized ([[first], [shared]] ++ later)).2.flatten.flatMap
          publicationAtoms
        = initial.nonterminalAtoms [[first], [shared]] ++ [.workQueueTermination] := by
  have stable := initial.runNormalized_termination_stable [[first], [shared]] later
    exact_nonterminal_history.2.2
  constructor
  · simp only [State.nonterminalAtoms, stable]
  · rw [stable, initial.runNormalized_terminalShape _ (createWorkQueue_terminated _),
      exact_nonterminal_history.2.2]
    rfl

private def stream : DeliveryNode := ⟨0, [.field "xs"], none⟩
private def streamWork : Execution.Work := .stream stream []
private def streamQueue : State := State.initialize (Work.fromExecution streamWork)

/-- Even an exhausted stream waits for its explicit host exhaustion event.
Witness: initialization is nonterminal, and the closure is retained before the one marker.
This raw finite stream checks the shape theorem's broader-than-generated domain.
-/
theorem empty_stream_boundary
    : streamQueue.terminated = false
      ∧ streamQueue.nonterminalAtoms [] = []
      ∧ streamQueue.nonterminalAtoms [[.streamSuccess stream]] = [.streamSuccess stream]
      ∧ (streamQueue.runNormalized [[.streamSuccess stream]]).2
        = [[.streamSuccess stream, .workQueueTermination]] := by
  exact ⟨createWorkQueue_terminated _, by cbv, by cbv, by cbv⟩

end GraphQL.IncrementalDelivery.Tests.WorkSchedulerTermination
